(* @NESTEDCOMMENTS := 'Yes' *)
(* @PATH := '' *)
(* @OBJECTFLAGS := '0, 8' *)
TYPE ST_SENSOR_TEMP :
STRUCT
	Name : STRING;
	Desc : STRING;

	Raw : REAL;
	Err : BOOL;
	Deg : REAL;

	(*Calib*)
	Cal_K   : REAL;
	Cal_Off : REAL;

	(*Avg*)
	Avg_Buf : ARRAY[0..4] OF REAL;
	Avg_Sum : LREAL;
	Avg_Pos : INT;

	(*Alarm*)
	Alarm : ST_ALARM;

	MinRaw : REAL :=  2.0;
	MaxRaw : REAL := 22.0;

	LowDeg : REAL;
	HigDeg : REAL;
	MaxDeg : REAL;

	Delay  : REAL;
	Count  : REAL;

	AlErr : BOOL;
	AlLow : BOOL;
	AlHig : BOOL;
	AlMax : BOOL;

	AdverLv  : UINT;
	AdverVal : REAL;

END_STRUCT
END_TYPE
(* @END_DECLARATION := '0' *)
