(* @NESTEDCOMMENTS := 'Yes' *)
(* @PATH := '' *)
(* @OBJECTFLAGS := '0, 8' *)
TYPE ST_SENSOR_POS :
STRUCT
	Name : STRING;
	Desc : STRING;

	Raw : REAL;
	Err : BOOL;
	Pos : REAL;

	(*Calib*)
	Cal_K   : REAL;
	Cal_Off : REAL;
	Cal_Min : REAL;
	Cal_Max : REAL;
	Cal_Apply : BOOL;

	(*Avg*)
	Avg_Buf : ARRAY[0..4] OF REAL;
	Avg_Sum : LREAL;
	Avg_Pos : INT;

	(*Alarm*)
	Alarm  : ST_ALARM;

	MinRaw : REAL :=  2.0;
	MaxRaw : REAL := 22.0;

END_STRUCT
END_TYPE
(* @END_DECLARATION := '0' *)
