(* @PATH := '' *)

VISUALISATION VISU_MAST_SETUP _VISU_TYPES : 1,1
_BG_BMP : 'visu_background.bmp'
_TEXT : 506
_PAINTZOOM : 100

_SIMPLE : 0
_LINEWIDTH : 0
_NOCOLORS : 0,0
_POS : 20,0,331,51,175,25
_COLORS : 16777215,0,16777215,0,16777215
_VARIABLES : '','','','','','','',''
_THRESH : '','','',''
_DSP : '','MAST SETUP',''
_ZOOM : ''
_INPUT : 0
_TEXT : 4,4294967264,700,0,56,0,0,0
_FONT : 'MS Sans Serif'
_EXEC : ''
_TEXTVARIABLES : '','','','',''
_COLORVARIABLES : '','','','','',''
_ACCESSLEVELS : 2,2,2,2,2,2,2,2
_OBJECT : 0,0
_THRESH2 : '','','',''
_INPUTTYPE : '','',''
_HIDDENINPUT : 0
_END_ELEM
(* @TEXTSCALINGVARS := '_TEXTSCALINGVARS: $'$',$'$'' *)
(* @EXTENDEDSIMPLESHAPE := '_SIMPLE: 0' *)
(* @INPUTTAPFALSE := '_INPUTTAPFALSE: 0' *)

_SIMPLE : 0
_LINEWIDTH : 0
_NOCOLORS : 0,0
_POS : 20,550,331,601,175,575
_COLORS : 16777215,0,16777215,0,16777215
_VARIABLES : '','','','','','','',''
_THRESH : '','','',''
_DSP : 'INPUTS.sVisuTime','%s',''
_ZOOM : ''
_INPUT : 0
_TEXT : 4,4294967264,700,0,153,0,0,0
_FONT : 'MS Sans Serif'
_EXEC : ''
_TEXTVARIABLES : '','','','',''
_COLORVARIABLES : '','','','','',''
_ACCESSLEVELS : 2,2,2,2,2,2,2,2
_OBJECT : 0,0
_THRESH2 : '','','',''
_INPUTTYPE : '','',''
_HIDDENINPUT : 0
_END_ELEM
(* @TEXTSCALINGVARS := '_TEXTSCALINGVARS: $'$',$'$'' *)
(* @EXTENDEDSIMPLESHAPE := '_SIMPLE: 0' *)
(* @INPUTTAPFALSE := '_INPUTTAPFALSE: 0' *)

_SIMPLE : 1
_LINEWIDTH : 0
_NOCOLORS : 1,1
_POS : 900,50,1021,101,960,75
_COLORS : 16777215,0,16777215,0,0
_VARIABLES : '','','','','','','',''
_THRESH : '','','',''
_DSP : '','',''
_ZOOM : ''
_INPUT : 0
_TEXT : 5,4294967284,400,0,312,0,0,0
_FONT : ''
_EXEC : ''
_TEXTVARIABLES : '','','','',''
_COLORVARIABLES : '','','','','',''
_ACCESSLEVELS : 2,2,2,2,2,2,2,2
_OBJECT : 0,0
_THRESH2 : '','','',''
_INPUTTYPE : '','',''
_HIDDENINPUT : 0
_END_ELEM
(* @TEXTSCALINGVARS := '_TEXTSCALINGVARS: $'$',$'$'' *)
(* @EXTENDEDSIMPLESHAPE := '_SIMPLE: 0' *)
(* @INPUTTAPFALSE := '_INPUTTAPFALSE: 0' *)

_SIMPLE : 1
_LINEWIDTH : 0
_NOCOLORS : 1,1
_POS : 905,55,1016,96,960,75
_COLORS : 12615680,0,8404992,0,16777215
_VARIABLES : '','','','','','','',''
_THRESH : '','PARAMS.Save','PARAMS.Save',''
_DSP : '','SAVE',''
_ZOOM : ''
_INPUT : 65536
_TEXT : 5,4294967283,700,0,313,0,0,0
_FONT : 'MS Sans Serif'
_EXEC : ''
_TEXTVARIABLES : '','','','',''
_COLORVARIABLES : '','','','','',''
_ACCESSLEVELS : 2,2,2,2,2,2,2,2
_OBJECT : 0,0
_THRESH2 : '','','',''
_INPUTTYPE : '','',''
_HIDDENINPUT : 0
_END_ELEM
(* @TEXTSCALINGVARS := '_TEXTSCALINGVARS: $'$',$'$'' *)
(* @EXTENDEDSIMPLESHAPE := '_SIMPLE: 0' *)
(* @INPUTTAPFALSE := '_INPUTTAPFALSE: 0' *)

_SIMPLE : 1
_LINEWIDTH : 0
_NOCOLORS : 1,1
_POS : 900,500,1021,551,960,525
_COLORS : 16777215,0,16777215,0,0
_VARIABLES : '','','','','','','',''
_THRESH : '','','',''
_DSP : '','',''
_ZOOM : ''
_INPUT : 0
_TEXT : 5,4294967284,400,0,314,0,0,0
_FONT : ''
_EXEC : ''
_TEXTVARIABLES : '','','','',''
_COLORVARIABLES : '','','','','',''
_ACCESSLEVELS : 2,2,2,2,2,2,2,2
_OBJECT : 0,0
_THRESH2 : '','','',''
_INPUTTYPE : '','',''
_HIDDENINPUT : 0
_END_ELEM
(* @TEXTSCALINGVARS := '_TEXTSCALINGVARS: $'$',$'$'' *)
(* @EXTENDEDSIMPLESHAPE := '_SIMPLE: 0' *)
(* @INPUTTAPFALSE := '_INPUTTAPFALSE: 0' *)

_SIMPLE : 1
_LINEWIDTH : 0
_NOCOLORS : 1,1
_POS : 905,505,1016,546,960,525
_COLORS : 2105379,0,16777215,0,16777215
_VARIABLES : '','','','','','','',''
_THRESH : '','','',''
_DSP : '','RETURN',''
_ZOOM : 'VISU_1_CYLINDERS1'
_INPUT : 262144
_TEXT : 5,4294967283,700,0,315,0,0,0
_FONT : 'MS Sans Serif'
_EXEC : ''
_TEXTVARIABLES : '','','','',''
_COLORVARIABLES : '','','','','',''
_ACCESSLEVELS : 2,2,2,2,2,2,2,2
_OBJECT : 0,0
_THRESH2 : '','','',''
_INPUTTYPE : '','',''
_HIDDENINPUT : 0
_END_ELEM
(* @TEXTSCALINGVARS := '_TEXTSCALINGVARS: $'$',$'$'' *)
(* @EXTENDEDSIMPLESHAPE := '_SIMPLE: 0' *)
(* @INPUTTAPFALSE := '_INPUTTAPFALSE: 0' *)

_SIMPLE : 0
_LINEWIDTH : 0
_NOCOLORS : 1,1
_POS : 20,70,541,471,280,270
_COLORS : 12828343,0,16777215,0,0
_VARIABLES : '','','','','','','',''
_THRESH : '','','',''
_DSP : '','',''
_ZOOM : ''
_INPUT : 0
_TEXT : 5,4294967284,400,0,341,0,0,0
_FONT : ''
_EXEC : ''
_TEXTVARIABLES : '','','','',''
_COLORVARIABLES : '','','','','',''
_ACCESSLEVELS : 2,2,2,2,2,2,2,2
_OBJECT : 0,0
_THRESH2 : '','','',''
_INPUTTYPE : '','',''
_HIDDENINPUT : 0
_END_ELEM
(* @TEXTSCALINGVARS := '_TEXTSCALINGVARS: $'$',$'$'' *)
(* @EXTENDEDSIMPLESHAPE := '_SIMPLE: 0' *)
(* @INPUTTAPFALSE := '_INPUTTAPFALSE: 0' *)

_SIMPLE : 0
_LINEWIDTH : 0
_NOCOLORS : 1,1
_POS : 210,115,301,136,255,125
_COLORS : 16777215,0,16777215,0,0
_VARIABLES : '','','','','','','',''
_THRESH : '','','',''
_DSP : 'PARAMS.stMastSetup.aTDef[4,1]','%.0f %% ',''
_ZOOM : ''
_INPUT : 1048576
_TEXT : 6,4294967283,400,0,386,0,0,0
_FONT : 'MS Sans Serif'
_EXEC : 'INTERN ASSIGN INPUTS.PresSelCalStbd[9]:=(FALSE)'
_TEXTVARIABLES : '','','','',''
_COLORVARIABLES : '','','','','',''
_ACCESSLEVELS : 2,2,2,2,2,2,2,2
_OBJECT : 0,1
_THRESH2 : '','','',''
_INPUTTYPE : '','',''
_HIDDENINPUT : 0
_END_ELEM
(* @TEXTSCALINGVARS := '_TEXTSCALINGVARS: $'$',$'$'' *)
(* @EXTENDEDSIMPLESHAPE := '_SIMPLE: 0' *)
(* @INPUTTAPFALSE := '_INPUTTAPFALSE: 0' *)

_SIMPLE : 0
_LINEWIDTH : 0
_NOCOLORS : 1,1
_POS : 210,135,301,156,255,145
_COLORS : 16777215,0,16777215,0,0
_VARIABLES : '','','','','','','',''
_THRESH : '','','',''
_DSP : 'PARAMS.stMastSetup.aTDef[4,5]','%.0f %% ',''
_ZOOM : ''
_INPUT : 1048576
_TEXT : 6,4294967283,400,0,387,0,0,0
_FONT : 'MS Sans Serif'
_EXEC : 'INTERN ASSIGN INPUTS.PresSelCalStbd[9]:=(FALSE)'
_TEXTVARIABLES : '','','','',''
_COLORVARIABLES : '','','','','',''
_ACCESSLEVELS : 2,2,2,2,2,2,2,2
_OBJECT : 0,1
_THRESH2 : '','','',''
_INPUTTYPE : '','',''
_HIDDENINPUT : 0
_END_ELEM
(* @TEXTSCALINGVARS := '_TEXTSCALINGVARS: $'$',$'$'' *)
(* @EXTENDEDSIMPLESHAPE := '_SIMPLE: 0' *)
(* @INPUTTAPFALSE := '_INPUTTAPFALSE: 0' *)

_SIMPLE : 0
_LINEWIDTH : 0
_NOCOLORS : 1,1
_POS : 210,180,301,201,255,190
_COLORS : 16777215,0,16777215,0,0
_VARIABLES : '','','','','','','',''
_THRESH : '','','',''
_DSP : 'PARAMS.stMastSetup.aTDef[4,2]','%.0f %% ',''
_ZOOM : ''
_INPUT : 1048576
_TEXT : 6,4294967283,400,0,388,0,0,0
_FONT : 'MS Sans Serif'
_EXEC : 'INTERN ASSIGN INPUTS.PresSelCalStbd[9]:=(FALSE)'
_TEXTVARIABLES : '','','','',''
_COLORVARIABLES : '','','','','',''
_ACCESSLEVELS : 2,2,2,2,2,2,2,2
_OBJECT : 0,1
_THRESH2 : '','','',''
_INPUTTYPE : '','',''
_HIDDENINPUT : 0
_END_ELEM
(* @TEXTSCALINGVARS := '_TEXTSCALINGVARS: $'$',$'$'' *)
(* @EXTENDEDSIMPLESHAPE := '_SIMPLE: 0' *)
(* @INPUTTAPFALSE := '_INPUTTAPFALSE: 0' *)

_SIMPLE : 0
_LINEWIDTH : 0
_NOCOLORS : 1,1
_POS : 210,200,301,221,255,210
_COLORS : 16777215,0,16777215,0,0
_VARIABLES : '','','','','','','',''
_THRESH : '','','',''
_DSP : 'PARAMS.stMastSetup.aTDef[4,6]','%.0f %% ',''
_ZOOM : ''
_INPUT : 1048576
_TEXT : 6,4294967283,400,0,389,0,0,0
_FONT : 'MS Sans Serif'
_EXEC : 'INTERN ASSIGN INPUTS.PresSelCalStbd[9]:=(FALSE)'
_TEXTVARIABLES : '','','','',''
_COLORVARIABLES : '','','','','',''
_ACCESSLEVELS : 2,2,2,2,2,2,2,2
_OBJECT : 0,1
_THRESH2 : '','','',''
_INPUTTYPE : '','',''
_HIDDENINPUT : 0
_END_ELEM
(* @TEXTSCALINGVARS := '_TEXTSCALINGVARS: $'$',$'$'' *)
(* @EXTENDEDSIMPLESHAPE := '_SIMPLE: 0' *)
(* @INPUTTAPFALSE := '_INPUTTAPFALSE: 0' *)

_SIMPLE : 0
_LINEWIDTH : 0
_NOCOLORS : 0,0
_POS : 60,115,191,136,125,125
_COLORS : 16777215,0,16777215,0,0
_VARIABLES : '','','','','','','',''
_THRESH : '','','',''
_DSP : 'RECV_J1939.F004.DriverDemandTorque','FULL HOIST$T- A3',''
_ZOOM : ''
_INPUT : 0
_TEXT : 4,4294967284,400,0,391,0,0,0
_FONT : ''
_EXEC : ''
_TEXTVARIABLES : '','','','',''
_COLORVARIABLES : '','','','','',''
_ACCESSLEVELS : 2,2,2,2,2,2,2,2
_OBJECT : 0,0
_THRESH2 : '','','',''
_INPUTTYPE : '','',''
_HIDDENINPUT : 0
_END_ELEM
(* @TEXTSCALINGVARS := '_TEXTSCALINGVARS: $'$',$'$'' *)
(* @EXTENDEDSIMPLESHAPE := '_SIMPLE: 0' *)
(* @INPUTTAPFALSE := '_INPUTTAPFALSE: 0' *)

_SIMPLE : 0
_LINEWIDTH : 0
_NOCOLORS : 0,0
_POS : 60,180,191,201,125,190
_COLORS : 16777215,0,16777215,0,0
_VARIABLES : '','','','','','','',''
_THRESH : '','','',''
_DSP : 'RECV_J1939.F004.DriverDemandTorque','FULL HOIST$T- Fr0',''
_ZOOM : ''
_INPUT : 0
_TEXT : 4,4294967284,400,0,393,0,0,0
_FONT : ''
_EXEC : ''
_TEXTVARIABLES : '','','','',''
_COLORVARIABLES : '','','','','',''
_ACCESSLEVELS : 2,2,2,2,2,2,2,2
_OBJECT : 0,0
_THRESH2 : '','','',''
_INPUTTYPE : '','',''
_HIDDENINPUT : 0
_END_ELEM
(* @TEXTSCALINGVARS := '_TEXTSCALINGVARS: $'$',$'$'' *)
(* @EXTENDEDSIMPLESHAPE := '_SIMPLE: 0' *)
(* @INPUTTAPFALSE := '_INPUTTAPFALSE: 0' *)

_SIMPLE : 0
_LINEWIDTH : 0
_NOCOLORS : 0,0
_POS : 60,200,191,221,125,210
_COLORS : 16777215,0,16777215,0,0
_VARIABLES : '','','','','','','',''
_THRESH : '','','',''
_DSP : 'RECV_J1939.F004.DriverDemandTorque','FULL HOIST$T- Fr0 + J4',''
_ZOOM : ''
_INPUT : 0
_TEXT : 4,4294967284,400,0,394,0,0,0
_FONT : ''
_EXEC : ''
_TEXTVARIABLES : '','','','',''
_COLORVARIABLES : '','','','','',''
_ACCESSLEVELS : 2,2,2,2,2,2,2,2
_OBJECT : 0,0
_THRESH2 : '','','',''
_INPUTTYPE : '','',''
_HIDDENINPUT : 0
_END_ELEM
(* @TEXTSCALINGVARS := '_TEXTSCALINGVARS: $'$',$'$'' *)
(* @EXTENDEDSIMPLESHAPE := '_SIMPLE: 0' *)
(* @INPUTTAPFALSE := '_INPUTTAPFALSE: 0' *)

_SIMPLE : 0
_LINEWIDTH : 0
_NOCOLORS : 1,1
_POS : 210,240,301,261,255,250
_COLORS : 16777215,0,16777215,0,0
_VARIABLES : '','','','','','','',''
_THRESH : '','','',''
_DSP : 'PARAMS.stMastSetup.aTDef[1,6]','%.0f %% ',''
_ZOOM : ''
_INPUT : 1048576
_TEXT : 6,4294967283,400,0,411,0,0,0
_FONT : 'MS Sans Serif'
_EXEC : 'INTERN ASSIGN INPUTS.PresSelCalStbd[9]:=(FALSE)'
_TEXTVARIABLES : '','','','',''
_COLORVARIABLES : '','','','','',''
_ACCESSLEVELS : 2,2,2,2,2,2,2,2
_OBJECT : 0,1
_THRESH2 : '','','',''
_INPUTTYPE : '','',''
_HIDDENINPUT : 0
_END_ELEM
(* @TEXTSCALINGVARS := '_TEXTSCALINGVARS: $'$',$'$'' *)
(* @EXTENDEDSIMPLESHAPE := '_SIMPLE: 0' *)
(* @INPUTTAPFALSE := '_INPUTTAPFALSE: 0' *)

_SIMPLE : 0
_LINEWIDTH : 0
_NOCOLORS : 1,1
_POS : 210,260,301,281,255,270
_COLORS : 16777215,0,16777215,0,0
_VARIABLES : '','','','','','','',''
_THRESH : '','','',''
_DSP : 'PARAMS.stMastSetup.aTDef[2,2]','%.0f %% ',''
_ZOOM : ''
_INPUT : 1048576
_TEXT : 6,4294967283,400,0,412,0,0,0
_FONT : 'MS Sans Serif'
_EXEC : 'INTERN ASSIGN INPUTS.PresSelCalStbd[9]:=(FALSE)'
_TEXTVARIABLES : '','','','',''
_COLORVARIABLES : '','','','','',''
_ACCESSLEVELS : 2,2,2,2,2,2,2,2
_OBJECT : 0,1
_THRESH2 : '','','',''
_INPUTTYPE : '','',''
_HIDDENINPUT : 0
_END_ELEM
(* @TEXTSCALINGVARS := '_TEXTSCALINGVARS: $'$',$'$'' *)
(* @EXTENDEDSIMPLESHAPE := '_SIMPLE: 0' *)
(* @INPUTTAPFALSE := '_INPUTTAPFALSE: 0' *)

_SIMPLE : 0
_LINEWIDTH : 0
_NOCOLORS : 0,0
_POS : 60,240,191,261,125,250
_COLORS : 16777215,0,16777215,0,0
_VARIABLES : '','','','','','','',''
_THRESH : '','','',''
_DSP : 'RECV_J1939.F004.DriverDemandTorque','1st REEF$T- Fr0 + J4',''
_ZOOM : ''
_INPUT : 0
_TEXT : 4,4294967284,400,0,413,0,0,0
_FONT : ''
_EXEC : ''
_TEXTVARIABLES : '','','','',''
_COLORVARIABLES : '','','','','',''
_ACCESSLEVELS : 2,2,2,2,2,2,2,2
_OBJECT : 0,0
_THRESH2 : '','','',''
_INPUTTYPE : '','',''
_HIDDENINPUT : 0
_END_ELEM
(* @TEXTSCALINGVARS := '_TEXTSCALINGVARS: $'$',$'$'' *)
(* @EXTENDEDSIMPLESHAPE := '_SIMPLE: 0' *)
(* @INPUTTAPFALSE := '_INPUTTAPFALSE: 0' *)

_SIMPLE : 0
_LINEWIDTH : 0
_NOCOLORS : 0,0
_POS : 60,260,191,281,125,270
_COLORS : 16777215,0,16777215,0,0
_VARIABLES : '','','','','','','',''
_THRESH : '','','',''
_DSP : 'RECV_J1939.F004.DriverDemandTorque','2nd REEF$T- Fr0',''
_ZOOM : ''
_INPUT : 0
_TEXT : 4,4294967284,400,0,414,0,0,0
_FONT : ''
_EXEC : ''
_TEXTVARIABLES : '','','','',''
_COLORVARIABLES : '','','','','',''
_ACCESSLEVELS : 2,2,2,2,2,2,2,2
_OBJECT : 0,0
_THRESH2 : '','','',''
_INPUTTYPE : '','',''
_HIDDENINPUT : 0
_END_ELEM
(* @TEXTSCALINGVARS := '_TEXTSCALINGVARS: $'$',$'$'' *)
(* @EXTENDEDSIMPLESHAPE := '_SIMPLE: 0' *)
(* @INPUTTAPFALSE := '_INPUTTAPFALSE: 0' *)

_SIMPLE : 0
_LINEWIDTH : 0
_NOCOLORS : 1,1
_POS : 210,155,301,176,255,165
_COLORS : 16777215,0,16777215,0,0
_VARIABLES : '','','','','','','',''
_THRESH : '','','',''
_DSP : 'PARAMS.stMastSetup.aTDef[1,1]','%.0f %% ',''
_ZOOM : ''
_INPUT : 1048576
_TEXT : 6,4294967283,400,0,428,0,0,0
_FONT : 'MS Sans Serif'
_EXEC : 'INTERN ASSIGN INPUTS.PresSelCalStbd[9]:=(FALSE)'
_TEXTVARIABLES : '','','','',''
_COLORVARIABLES : '','','','','',''
_ACCESSLEVELS : 2,2,2,2,2,2,2,2
_OBJECT : 0,1
_THRESH2 : '','','',''
_INPUTTYPE : '','',''
_HIDDENINPUT : 0
_END_ELEM
(* @TEXTSCALINGVARS := '_TEXTSCALINGVARS: $'$',$'$'' *)
(* @EXTENDEDSIMPLESHAPE := '_SIMPLE: 0' *)
(* @INPUTTAPFALSE := '_INPUTTAPFALSE: 0' *)

_SIMPLE : 0
_LINEWIDTH : 0
_NOCOLORS : 0,0
_POS : 60,155,191,176,125,165
_COLORS : 16777215,0,16777215,0,0
_VARIABLES : '','','','','','','',''
_THRESH : '','','',''
_DSP : 'RECV_J1939.F004.DriverDemandTorque','1st REEF$T- A3',''
_ZOOM : ''
_INPUT : 0
_TEXT : 4,4294967284,400,0,429,0,0,0
_FONT : ''
_EXEC : ''
_TEXTVARIABLES : '','','','',''
_COLORVARIABLES : '','','','','',''
_ACCESSLEVELS : 2,2,2,2,2,2,2,2
_OBJECT : 0,0
_THRESH2 : '','','',''
_INPUTTYPE : '','',''
_HIDDENINPUT : 0
_END_ELEM
(* @TEXTSCALINGVARS := '_TEXTSCALINGVARS: $'$',$'$'' *)
(* @EXTENDEDSIMPLESHAPE := '_SIMPLE: 0' *)
(* @INPUTTAPFALSE := '_INPUTTAPFALSE: 0' *)

_SIMPLE : 0
_LINEWIDTH : 0
_NOCOLORS : 0,0
_POS : 730,550,896,601,813,575
_COLORS : 16777215,0,16777215,0,16777215
_VARIABLES : '','','','','','','',''
_THRESH : 'PARAMS.Saved','','',''
_DSP : '','SAVED!',''
_ZOOM : ''
_INPUT : 0
_TEXT : 5,4294967264,700,0,430,0,0,0
_FONT : 'MS Sans Serif'
_EXEC : ''
_TEXTVARIABLES : '','','','',''
_COLORVARIABLES : '','','','','',''
_ACCESSLEVELS : 2,2,2,2,2,2,2,2
_OBJECT : 0,0
_THRESH2 : '','','',''
_INPUTTYPE : '','',''
_HIDDENINPUT : 0
_END_ELEM
(* @TEXTSCALINGVARS := '_TEXTSCALINGVARS: $'$',$'$'' *)
(* @EXTENDEDSIMPLESHAPE := '_SIMPLE: 0' *)
(* @INPUTTAPFALSE := '_INPUTTAPFALSE: 0' *)

_SIMPLE : 0
_LINEWIDTH : 0
_NOCOLORS : 1,1
_POS : 210,220,301,241,255,230
_COLORS : 16777215,0,16777215,0,0
_VARIABLES : '','','','','','','',''
_THRESH : '','','',''
_DSP : 'PARAMS.stMastSetup.aTDef[1,2]','%.0f %% ',''
_ZOOM : ''
_INPUT : 1048576
_TEXT : 6,4294967283,400,0,444,0,0,0
_FONT : 'MS Sans Serif'
_EXEC : 'INTERN ASSIGN INPUTS.PresSelCalStbd[9]:=(FALSE)'
_TEXTVARIABLES : '','','','',''
_COLORVARIABLES : '','','','','',''
_ACCESSLEVELS : 2,2,2,2,2,2,2,2
_OBJECT : 0,1
_THRESH2 : '','','',''
_INPUTTYPE : '','',''
_HIDDENINPUT : 0
_END_ELEM
(* @TEXTSCALINGVARS := '_TEXTSCALINGVARS: $'$',$'$'' *)
(* @EXTENDEDSIMPLESHAPE := '_SIMPLE: 0' *)
(* @INPUTTAPFALSE := '_INPUTTAPFALSE: 0' *)

_SIMPLE : 0
_LINEWIDTH : 0
_NOCOLORS : 0,0
_POS : 60,220,191,241,125,230
_COLORS : 16777215,0,16777215,0,0
_VARIABLES : '','','','','','','',''
_THRESH : '','','',''
_DSP : 'RECV_J1939.F004.DriverDemandTorque','1st REEF$T- Fr0',''
_ZOOM : ''
_INPUT : 0
_TEXT : 4,4294967284,400,0,445,0,0,0
_FONT : ''
_EXEC : ''
_TEXTVARIABLES : '','','','',''
_COLORVARIABLES : '','','','','',''
_ACCESSLEVELS : 2,2,2,2,2,2,2,2
_OBJECT : 0,0
_THRESH2 : '','','',''
_INPUTTYPE : '','',''
_HIDDENINPUT : 0
_END_ELEM
(* @TEXTSCALINGVARS := '_TEXTSCALINGVARS: $'$',$'$'' *)
(* @EXTENDEDSIMPLESHAPE := '_SIMPLE: 0' *)
(* @INPUTTAPFALSE := '_INPUTTAPFALSE: 0' *)

_SIMPLE : 0
_LINEWIDTH : 0
_NOCOLORS : 0,0
_POS : 60,135,191,156,125,145
_COLORS : 16777215,0,16777215,0,0
_VARIABLES : '','','','','','','',''
_THRESH : '','','',''
_DSP : 'RECV_J1939.F004.DriverDemandTorque','FULL HOIST$T- A3 + J4',''
_ZOOM : ''
_INPUT : 0
_TEXT : 4,4294967284,400,0,456,0,0,0
_FONT : ''
_EXEC : ''
_TEXTVARIABLES : '','','','',''
_COLORVARIABLES : '','','','','',''
_ACCESSLEVELS : 2,2,2,2,2,2,2,2
_OBJECT : 0,0
_THRESH2 : '','','',''
_INPUTTYPE : '','',''
_HIDDENINPUT : 0
_END_ELEM
(* @TEXTSCALINGVARS := '_TEXTSCALINGVARS: $'$',$'$'' *)
(* @EXTENDEDSIMPLESHAPE := '_SIMPLE: 0' *)
(* @INPUTTAPFALSE := '_INPUTTAPFALSE: 0' *)

_SIMPLE : 0
_LINEWIDTH : 0
_NOCOLORS : 0,1
_POS : 210,95,301,116,255,105
_COLORS : 12828343,8388608,16776960,16777215,0
_VARIABLES : '','','','','','','',''
_THRESH : '','','',''
_DSP : '','TOP DEF.',''
_ZOOM : ''
_INPUT : 0
_TEXT : 5,4294967285,400,0,458,0,0,0
_FONT : 'MS Sans Serif'
_EXEC : ''
_TEXTVARIABLES : '','','','',''
_COLORVARIABLES : '','','','','',''
_ACCESSLEVELS : 2,2,2,2,2,2,2,2
_OBJECT : 0,0
_THRESH2 : '','','',''
_INPUTTYPE : '','',''
_HIDDENINPUT : 0
_END_ELEM
(* @TEXTSCALINGVARS := '_TEXTSCALINGVARS: $'$',$'$'' *)
(* @EXTENDEDSIMPLESHAPE := '_SIMPLE: 0' *)
(* @INPUTTAPFALSE := '_INPUTTAPFALSE: 0' *)

_SIMPLE : 0
_LINEWIDTH : 0
_NOCOLORS : 1,1
_POS : 210,285,301,306,255,295
_COLORS : 16777215,0,16777215,0,0
_VARIABLES : '','','','','','','',''
_THRESH : '','','',''
_DSP : 'PARAMS.stMastSetup.aTDef[4,3]','%.0f %% ',''
_ZOOM : ''
_INPUT : 1048576
_TEXT : 6,4294967283,400,0,459,0,0,0
_FONT : 'MS Sans Serif'
_EXEC : 'INTERN ASSIGN INPUTS.PresSelCalStbd[9]:=(FALSE)'
_TEXTVARIABLES : '','','','',''
_COLORVARIABLES : '','','','','',''
_ACCESSLEVELS : 2,2,2,2,2,2,2,2
_OBJECT : 0,1
_THRESH2 : '','','',''
_INPUTTYPE : '','',''
_HIDDENINPUT : 0
_END_ELEM
(* @TEXTSCALINGVARS := '_TEXTSCALINGVARS: $'$',$'$'' *)
(* @EXTENDEDSIMPLESHAPE := '_SIMPLE: 0' *)
(* @INPUTTAPFALSE := '_INPUTTAPFALSE: 0' *)

_SIMPLE : 0
_LINEWIDTH : 0
_NOCOLORS : 1,1
_POS : 210,325,301,346,255,335
_COLORS : 16777215,0,16777215,0,0
_VARIABLES : '','','','','','','',''
_THRESH : '','','',''
_DSP : 'PARAMS.stMastSetup.aTDef[2,3]','%.0f %% ',''
_ZOOM : ''
_INPUT : 1048576
_TEXT : 6,4294967283,400,0,460,0,0,0
_FONT : 'MS Sans Serif'
_EXEC : 'INTERN ASSIGN INPUTS.PresSelCalStbd[9]:=(FALSE)'
_TEXTVARIABLES : '','','','',''
_COLORVARIABLES : '','','','','',''
_ACCESSLEVELS : 2,2,2,2,2,2,2,2
_OBJECT : 0,1
_THRESH2 : '','','',''
_INPUTTYPE : '','',''
_HIDDENINPUT : 0
_END_ELEM
(* @TEXTSCALINGVARS := '_TEXTSCALINGVARS: $'$',$'$'' *)
(* @EXTENDEDSIMPLESHAPE := '_SIMPLE: 0' *)
(* @INPUTTAPFALSE := '_INPUTTAPFALSE: 0' *)

_SIMPLE : 0
_LINEWIDTH : 0
_NOCOLORS : 1,1
_POS : 210,305,301,326,255,315
_COLORS : 16777215,0,16777215,0,0
_VARIABLES : '','','','','','','',''
_THRESH : '','','',''
_DSP : 'PARAMS.stMastSetup.aTDef[1,3]','%.0f %% ',''
_ZOOM : ''
_INPUT : 1048576
_TEXT : 6,4294967283,400,0,461,0,0,0
_FONT : 'MS Sans Serif'
_EXEC : 'INTERN ASSIGN INPUTS.PresSelCalStbd[9]:=(FALSE)'
_TEXTVARIABLES : '','','','',''
_COLORVARIABLES : '','','','','',''
_ACCESSLEVELS : 2,2,2,2,2,2,2,2
_OBJECT : 0,1
_THRESH2 : '','','',''
_INPUTTYPE : '','',''
_HIDDENINPUT : 0
_END_ELEM
(* @TEXTSCALINGVARS := '_TEXTSCALINGVARS: $'$',$'$'' *)
(* @EXTENDEDSIMPLESHAPE := '_SIMPLE: 0' *)
(* @INPUTTAPFALSE := '_INPUTTAPFALSE: 0' *)

_SIMPLE : 0
_LINEWIDTH : 0
_NOCOLORS : 0,0
_POS : 60,285,191,306,125,295
_COLORS : 16777215,0,16777215,0,0
_VARIABLES : '','','','','','','',''
_THRESH : '','','',''
_DSP : 'RECV_J1939.F004.DriverDemandTorque','FULL HOIST$T- J2',''
_ZOOM : ''
_INPUT : 0
_TEXT : 4,4294967284,400,0,462,0,0,0
_FONT : ''
_EXEC : ''
_TEXTVARIABLES : '','','','',''
_COLORVARIABLES : '','','','','',''
_ACCESSLEVELS : 2,2,2,2,2,2,2,2
_OBJECT : 0,0
_THRESH2 : '','','',''
_INPUTTYPE : '','',''
_HIDDENINPUT : 0
_END_ELEM
(* @TEXTSCALINGVARS := '_TEXTSCALINGVARS: $'$',$'$'' *)
(* @EXTENDEDSIMPLESHAPE := '_SIMPLE: 0' *)
(* @INPUTTAPFALSE := '_INPUTTAPFALSE: 0' *)

_SIMPLE : 0
_LINEWIDTH : 0
_NOCOLORS : 0,0
_POS : 60,305,191,326,125,315
_COLORS : 16777215,0,16777215,0,0
_VARIABLES : '','','','','','','',''
_THRESH : '','','',''
_DSP : 'RECV_J1939.F004.DriverDemandTorque','1st REEF$T- J2',''
_ZOOM : ''
_INPUT : 0
_TEXT : 4,4294967284,400,0,463,0,0,0
_FONT : ''
_EXEC : ''
_TEXTVARIABLES : '','','','',''
_COLORVARIABLES : '','','','','',''
_ACCESSLEVELS : 2,2,2,2,2,2,2,2
_OBJECT : 0,0
_THRESH2 : '','','',''
_INPUTTYPE : '','',''
_HIDDENINPUT : 0
_END_ELEM
(* @TEXTSCALINGVARS := '_TEXTSCALINGVARS: $'$',$'$'' *)
(* @EXTENDEDSIMPLESHAPE := '_SIMPLE: 0' *)
(* @INPUTTAPFALSE := '_INPUTTAPFALSE: 0' *)

_SIMPLE : 0
_LINEWIDTH : 0
_NOCOLORS : 0,0
_POS : 60,325,191,346,125,335
_COLORS : 16777215,0,16777215,0,0
_VARIABLES : '','','','','','','',''
_THRESH : '','','',''
_DSP : 'RECV_J1939.F004.DriverDemandTorque','2nd REEF$T- J2',''
_ZOOM : ''
_INPUT : 0
_TEXT : 4,4294967284,400,0,464,0,0,0
_FONT : ''
_EXEC : ''
_TEXTVARIABLES : '','','','',''
_COLORVARIABLES : '','','','','',''
_ACCESSLEVELS : 2,2,2,2,2,2,2,2
_OBJECT : 0,0
_THRESH2 : '','','',''
_INPUTTYPE : '','',''
_HIDDENINPUT : 0
_END_ELEM
(* @TEXTSCALINGVARS := '_TEXTSCALINGVARS: $'$',$'$'' *)
(* @EXTENDEDSIMPLESHAPE := '_SIMPLE: 0' *)
(* @INPUTTAPFALSE := '_INPUTTAPFALSE: 0' *)

_SIMPLE : 0
_LINEWIDTH : 0
_NOCOLORS : 1,1
_POS : 210,350,301,371,255,360
_COLORS : 16777215,0,16777215,0,0
_VARIABLES : '','','','','','','',''
_THRESH : '','','',''
_DSP : 'PARAMS.stMastSetup.aTDef[4,4]','%.0f %% ',''
_ZOOM : ''
_INPUT : 1048576
_TEXT : 6,4294967283,400,0,465,0,0,0
_FONT : 'MS Sans Serif'
_EXEC : 'INTERN ASSIGN INPUTS.PresSelCalStbd[9]:=(FALSE)'
_TEXTVARIABLES : '','','','',''
_COLORVARIABLES : '','','','','',''
_ACCESSLEVELS : 2,2,2,2,2,2,2,2
_OBJECT : 0,1
_THRESH2 : '','','',''
_INPUTTYPE : '','',''
_HIDDENINPUT : 0
_END_ELEM
(* @TEXTSCALINGVARS := '_TEXTSCALINGVARS: $'$',$'$'' *)
(* @EXTENDEDSIMPLESHAPE := '_SIMPLE: 0' *)
(* @INPUTTAPFALSE := '_INPUTTAPFALSE: 0' *)

_SIMPLE : 0
_LINEWIDTH : 0
_NOCOLORS : 1,1
_POS : 210,390,301,411,255,400
_COLORS : 16777215,0,16777215,0,0
_VARIABLES : '','','','','','','',''
_THRESH : '','','',''
_DSP : 'PARAMS.stMastSetup.aTDef[2,4]','%.0f %% ',''
_ZOOM : ''
_INPUT : 1048576
_TEXT : 6,4294967283,400,0,466,0,0,0
_FONT : 'MS Sans Serif'
_EXEC : 'INTERN ASSIGN INPUTS.PresSelCalStbd[9]:=(FALSE)'
_TEXTVARIABLES : '','','','',''
_COLORVARIABLES : '','','','','',''
_ACCESSLEVELS : 2,2,2,2,2,2,2,2
_OBJECT : 0,1
_THRESH2 : '','','',''
_INPUTTYPE : '','',''
_HIDDENINPUT : 0
_END_ELEM
(* @TEXTSCALINGVARS := '_TEXTSCALINGVARS: $'$',$'$'' *)
(* @EXTENDEDSIMPLESHAPE := '_SIMPLE: 0' *)
(* @INPUTTAPFALSE := '_INPUTTAPFALSE: 0' *)

_SIMPLE : 0
_LINEWIDTH : 0
_NOCOLORS : 1,1
_POS : 210,370,301,391,255,380
_COLORS : 16777215,0,16777215,0,0
_VARIABLES : '','','','','','','',''
_THRESH : '','','',''
_DSP : 'PARAMS.stMastSetup.aTDef[1,4]','%.0f %% ',''
_ZOOM : ''
_INPUT : 1048576
_TEXT : 6,4294967283,400,0,467,0,0,0
_FONT : 'MS Sans Serif'
_EXEC : 'INTERN ASSIGN INPUTS.PresSelCalStbd[9]:=(FALSE)'
_TEXTVARIABLES : '','','','',''
_COLORVARIABLES : '','','','','',''
_ACCESSLEVELS : 2,2,2,2,2,2,2,2
_OBJECT : 0,1
_THRESH2 : '','','',''
_INPUTTYPE : '','',''
_HIDDENINPUT : 0
_END_ELEM
(* @TEXTSCALINGVARS := '_TEXTSCALINGVARS: $'$',$'$'' *)
(* @EXTENDEDSIMPLESHAPE := '_SIMPLE: 0' *)
(* @INPUTTAPFALSE := '_INPUTTAPFALSE: 0' *)

_SIMPLE : 0
_LINEWIDTH : 0
_NOCOLORS : 0,0
_POS : 60,350,191,371,125,360
_COLORS : 16777215,0,16777215,0,0
_VARIABLES : '','','','','','','',''
_THRESH : '','','',''
_DSP : 'RECV_J1939.F004.DriverDemandTorque','FULL HOIST$T- J4',''
_ZOOM : ''
_INPUT : 0
_TEXT : 4,4294967284,400,0,468,0,0,0
_FONT : ''
_EXEC : ''
_TEXTVARIABLES : '','','','',''
_COLORVARIABLES : '','','','','',''
_ACCESSLEVELS : 2,2,2,2,2,2,2,2
_OBJECT : 0,0
_THRESH2 : '','','',''
_INPUTTYPE : '','',''
_HIDDENINPUT : 0
_END_ELEM
(* @TEXTSCALINGVARS := '_TEXTSCALINGVARS: $'$',$'$'' *)
(* @EXTENDEDSIMPLESHAPE := '_SIMPLE: 0' *)
(* @INPUTTAPFALSE := '_INPUTTAPFALSE: 0' *)

_SIMPLE : 0
_LINEWIDTH : 0
_NOCOLORS : 0,0
_POS : 60,370,191,391,125,380
_COLORS : 16777215,0,16777215,0,0
_VARIABLES : '','','','','','','',''
_THRESH : '','','',''
_DSP : 'RECV_J1939.F004.DriverDemandTorque','1st REEF$T- J4',''
_ZOOM : ''
_INPUT : 0
_TEXT : 4,4294967284,400,0,469,0,0,0
_FONT : ''
_EXEC : ''
_TEXTVARIABLES : '','','','',''
_COLORVARIABLES : '','','','','',''
_ACCESSLEVELS : 2,2,2,2,2,2,2,2
_OBJECT : 0,0
_THRESH2 : '','','',''
_INPUTTYPE : '','',''
_HIDDENINPUT : 0
_END_ELEM
(* @TEXTSCALINGVARS := '_TEXTSCALINGVARS: $'$',$'$'' *)
(* @EXTENDEDSIMPLESHAPE := '_SIMPLE: 0' *)
(* @INPUTTAPFALSE := '_INPUTTAPFALSE: 0' *)

_SIMPLE : 0
_LINEWIDTH : 0
_NOCOLORS : 0,0
_POS : 60,390,191,411,125,400
_COLORS : 16777215,0,16777215,0,0
_VARIABLES : '','','','','','','',''
_THRESH : '','','',''
_DSP : 'RECV_J1939.F004.DriverDemandTorque','2nd REEF$T- J4',''
_ZOOM : ''
_INPUT : 0
_TEXT : 4,4294967284,400,0,470,0,0,0
_FONT : ''
_EXEC : ''
_TEXTVARIABLES : '','','','',''
_COLORVARIABLES : '','','','','',''
_ACCESSLEVELS : 2,2,2,2,2,2,2,2
_OBJECT : 0,0
_THRESH2 : '','','',''
_INPUTTYPE : '','',''
_HIDDENINPUT : 0
_END_ELEM
(* @TEXTSCALINGVARS := '_TEXTSCALINGVARS: $'$',$'$'' *)
(* @EXTENDEDSIMPLESHAPE := '_SIMPLE: 0' *)
(* @INPUTTAPFALSE := '_INPUTTAPFALSE: 0' *)

_SIMPLE : 0
_LINEWIDTH : 0
_NOCOLORS : 1,1
_POS : 210,410,301,431,255,420
_COLORS : 16777215,0,16777215,0,0
_VARIABLES : '','','','','','','',''
_THRESH : '','','',''
_DSP : 'PARAMS.stMastSetup.aTDef[3,4]','%.0f %% ',''
_ZOOM : ''
_INPUT : 1048576
_TEXT : 6,4294967283,400,0,471,0,0,0
_FONT : 'MS Sans Serif'
_EXEC : 'INTERN ASSIGN INPUTS.PresSelCalStbd[9]:=(FALSE)'
_TEXTVARIABLES : '','','','',''
_COLORVARIABLES : '','','','','',''
_ACCESSLEVELS : 2,2,2,2,2,2,2,2
_OBJECT : 0,1
_THRESH2 : '','','',''
_INPUTTYPE : '','',''
_HIDDENINPUT : 0
_END_ELEM
(* @TEXTSCALINGVARS := '_TEXTSCALINGVARS: $'$',$'$'' *)
(* @EXTENDEDSIMPLESHAPE := '_SIMPLE: 0' *)
(* @INPUTTAPFALSE := '_INPUTTAPFALSE: 0' *)

_SIMPLE : 0
_LINEWIDTH : 0
_NOCOLORS : 0,0
_POS : 60,410,191,431,125,420
_COLORS : 16777215,0,16777215,0,0
_VARIABLES : '','','','','','','',''
_THRESH : '','','',''
_DSP : 'RECV_J1939.F004.DriverDemandTorque','3rd REEF$T- J4',''
_ZOOM : ''
_INPUT : 0
_TEXT : 4,4294967284,400,0,472,0,0,0
_FONT : ''
_EXEC : ''
_TEXTVARIABLES : '','','','',''
_COLORVARIABLES : '','','','','',''
_ACCESSLEVELS : 2,2,2,2,2,2,2,2
_OBJECT : 0,0
_THRESH2 : '','','',''
_INPUTTYPE : '','',''
_HIDDENINPUT : 0
_END_ELEM
(* @TEXTSCALINGVARS := '_TEXTSCALINGVARS: $'$',$'$'' *)
(* @EXTENDEDSIMPLESHAPE := '_SIMPLE: 0' *)
(* @INPUTTAPFALSE := '_INPUTTAPFALSE: 0' *)

_SIMPLE : 0
_LINEWIDTH : 0
_NOCOLORS : 0,0
_POS : 60,95,206,116,133,105
_COLORS : 16777215,0,16777215,0,0
_VARIABLES : '','','','','','','',''
_THRESH : '','','',''
_DSP : 'RECV_J1939.F004.DriverDemandTorque','MAINSAIL$THEADSAIL',''
_ZOOM : ''
_INPUT : 0
_TEXT : 4,4294967284,400,0,473,0,0,0
_FONT : ''
_EXEC : ''
_TEXTVARIABLES : '','','','',''
_COLORVARIABLES : '','','','','',''
_ACCESSLEVELS : 2,2,2,2,2,2,2,2
_OBJECT : 0,0
_THRESH2 : '','','',''
_INPUTTYPE : '','',''
_HIDDENINPUT : 0
_END_ELEM
(* @TEXTSCALINGVARS := '_TEXTSCALINGVARS: $'$',$'$'' *)
(* @EXTENDEDSIMPLESHAPE := '_SIMPLE: 0' *)
(* @INPUTTAPFALSE := '_INPUTTAPFALSE: 0' *)

_SIMPLE : 0
_LINEWIDTH : 0
_NOCOLORS : 1,1
_POS : 305,115,396,136,350,125
_COLORS : 16777215,0,16777215,0,0
_VARIABLES : '','','','','','','',''
_THRESH : '','','',''
_DSP : 'PARAMS.stMastSetup.aBDef[4,1]','%.0f %% ',''
_ZOOM : ''
_INPUT : 1048576
_TEXT : 6,4294967283,400,0,474,0,0,0
_FONT : 'MS Sans Serif'
_EXEC : 'INTERN ASSIGN INPUTS.PresSelCalStbd[9]:=(FALSE)'
_TEXTVARIABLES : '','','','',''
_COLORVARIABLES : '','','','','',''
_ACCESSLEVELS : 2,2,2,2,2,2,2,2
_OBJECT : 0,1
_THRESH2 : '','','',''
_INPUTTYPE : '','',''
_HIDDENINPUT : 0
_END_ELEM
(* @TEXTSCALINGVARS := '_TEXTSCALINGVARS: $'$',$'$'' *)
(* @EXTENDEDSIMPLESHAPE := '_SIMPLE: 0' *)
(* @INPUTTAPFALSE := '_INPUTTAPFALSE: 0' *)

_SIMPLE : 0
_LINEWIDTH : 0
_NOCOLORS : 1,1
_POS : 305,135,396,156,350,145
_COLORS : 16777215,0,16777215,0,0
_VARIABLES : '','','','','','','',''
_THRESH : '','','',''
_DSP : 'PARAMS.stMastSetup.aBDef[4,5]','%.0f %% ',''
_ZOOM : ''
_INPUT : 1048576
_TEXT : 6,4294967283,400,0,475,0,0,0
_FONT : 'MS Sans Serif'
_EXEC : 'INTERN ASSIGN INPUTS.PresSelCalStbd[9]:=(FALSE)'
_TEXTVARIABLES : '','','','',''
_COLORVARIABLES : '','','','','',''
_ACCESSLEVELS : 2,2,2,2,2,2,2,2
_OBJECT : 0,1
_THRESH2 : '','','',''
_INPUTTYPE : '','',''
_HIDDENINPUT : 0
_END_ELEM
(* @TEXTSCALINGVARS := '_TEXTSCALINGVARS: $'$',$'$'' *)
(* @EXTENDEDSIMPLESHAPE := '_SIMPLE: 0' *)
(* @INPUTTAPFALSE := '_INPUTTAPFALSE: 0' *)

_SIMPLE : 0
_LINEWIDTH : 0
_NOCOLORS : 1,1
_POS : 305,180,396,201,350,190
_COLORS : 16777215,0,16777215,0,0
_VARIABLES : '','','','','','','',''
_THRESH : '','','',''
_DSP : 'PARAMS.stMastSetup.aBDef[4,2]','%.0f %% ',''
_ZOOM : ''
_INPUT : 1048576
_TEXT : 6,4294967283,400,0,476,0,0,0
_FONT : 'MS Sans Serif'
_EXEC : 'INTERN ASSIGN INPUTS.PresSelCalStbd[9]:=(FALSE)'
_TEXTVARIABLES : '','','','',''
_COLORVARIABLES : '','','','','',''
_ACCESSLEVELS : 2,2,2,2,2,2,2,2
_OBJECT : 0,1
_THRESH2 : '','','',''
_INPUTTYPE : '','',''
_HIDDENINPUT : 0
_END_ELEM
(* @TEXTSCALINGVARS := '_TEXTSCALINGVARS: $'$',$'$'' *)
(* @EXTENDEDSIMPLESHAPE := '_SIMPLE: 0' *)
(* @INPUTTAPFALSE := '_INPUTTAPFALSE: 0' *)

_SIMPLE : 0
_LINEWIDTH : 0
_NOCOLORS : 1,1
_POS : 305,200,396,221,350,210
_COLORS : 16777215,0,16777215,0,0
_VARIABLES : '','','','','','','',''
_THRESH : '','','',''
_DSP : 'PARAMS.stMastSetup.aBDef[4,6]','%.0f %% ',''
_ZOOM : ''
_INPUT : 1048576
_TEXT : 6,4294967283,400,0,477,0,0,0
_FONT : 'MS Sans Serif'
_EXEC : 'INTERN ASSIGN INPUTS.PresSelCalStbd[9]:=(FALSE)'
_TEXTVARIABLES : '','','','',''
_COLORVARIABLES : '','','','','',''
_ACCESSLEVELS : 2,2,2,2,2,2,2,2
_OBJECT : 0,1
_THRESH2 : '','','',''
_INPUTTYPE : '','',''
_HIDDENINPUT : 0
_END_ELEM
(* @TEXTSCALINGVARS := '_TEXTSCALINGVARS: $'$',$'$'' *)
(* @EXTENDEDSIMPLESHAPE := '_SIMPLE: 0' *)
(* @INPUTTAPFALSE := '_INPUTTAPFALSE: 0' *)

_SIMPLE : 0
_LINEWIDTH : 0
_NOCOLORS : 1,1
_POS : 305,240,396,261,350,250
_COLORS : 16777215,0,16777215,0,0
_VARIABLES : '','','','','','','',''
_THRESH : '','','',''
_DSP : 'PARAMS.stMastSetup.aBDef[1,6]','%.0f %% ',''
_ZOOM : ''
_INPUT : 1048576
_TEXT : 6,4294967283,400,0,478,0,0,0
_FONT : 'MS Sans Serif'
_EXEC : 'INTERN ASSIGN INPUTS.PresSelCalStbd[9]:=(FALSE)'
_TEXTVARIABLES : '','','','',''
_COLORVARIABLES : '','','','','',''
_ACCESSLEVELS : 2,2,2,2,2,2,2,2
_OBJECT : 0,1
_THRESH2 : '','','',''
_INPUTTYPE : '','',''
_HIDDENINPUT : 0
_END_ELEM
(* @TEXTSCALINGVARS := '_TEXTSCALINGVARS: $'$',$'$'' *)
(* @EXTENDEDSIMPLESHAPE := '_SIMPLE: 0' *)
(* @INPUTTAPFALSE := '_INPUTTAPFALSE: 0' *)

_SIMPLE : 0
_LINEWIDTH : 0
_NOCOLORS : 1,1
_POS : 305,260,396,281,350,270
_COLORS : 16777215,0,16777215,0,0
_VARIABLES : '','','','','','','',''
_THRESH : '','','',''
_DSP : 'PARAMS.stMastSetup.aBDef[2,2]','%.0f %% ',''
_ZOOM : ''
_INPUT : 1048576
_TEXT : 6,4294967283,400,0,479,0,0,0
_FONT : 'MS Sans Serif'
_EXEC : 'INTERN ASSIGN INPUTS.PresSelCalStbd[9]:=(FALSE)'
_TEXTVARIABLES : '','','','',''
_COLORVARIABLES : '','','','','',''
_ACCESSLEVELS : 2,2,2,2,2,2,2,2
_OBJECT : 0,1
_THRESH2 : '','','',''
_INPUTTYPE : '','',''
_HIDDENINPUT : 0
_END_ELEM
(* @TEXTSCALINGVARS := '_TEXTSCALINGVARS: $'$',$'$'' *)
(* @EXTENDEDSIMPLESHAPE := '_SIMPLE: 0' *)
(* @INPUTTAPFALSE := '_INPUTTAPFALSE: 0' *)

_SIMPLE : 0
_LINEWIDTH : 0
_NOCOLORS : 1,1
_POS : 305,155,396,176,350,165
_COLORS : 16777215,0,16777215,0,0
_VARIABLES : '','','','','','','',''
_THRESH : '','','',''
_DSP : 'PARAMS.stMastSetup.aBDef[1,1]','%.0f %% ',''
_ZOOM : ''
_INPUT : 1048576
_TEXT : 6,4294967283,400,0,480,0,0,0
_FONT : 'MS Sans Serif'
_EXEC : 'INTERN ASSIGN INPUTS.PresSelCalStbd[9]:=(FALSE)'
_TEXTVARIABLES : '','','','',''
_COLORVARIABLES : '','','','','',''
_ACCESSLEVELS : 2,2,2,2,2,2,2,2
_OBJECT : 0,1
_THRESH2 : '','','',''
_INPUTTYPE : '','',''
_HIDDENINPUT : 0
_END_ELEM
(* @TEXTSCALINGVARS := '_TEXTSCALINGVARS: $'$',$'$'' *)
(* @EXTENDEDSIMPLESHAPE := '_SIMPLE: 0' *)
(* @INPUTTAPFALSE := '_INPUTTAPFALSE: 0' *)

_SIMPLE : 0
_LINEWIDTH : 0
_NOCOLORS : 1,1
_POS : 305,220,396,241,350,230
_COLORS : 16777215,0,16777215,0,0
_VARIABLES : '','','','','','','',''
_THRESH : '','','',''
_DSP : 'PARAMS.stMastSetup.aBDef[1,2]','%.0f %% ',''
_ZOOM : ''
_INPUT : 1048576
_TEXT : 6,4294967283,400,0,481,0,0,0
_FONT : 'MS Sans Serif'
_EXEC : 'INTERN ASSIGN INPUTS.PresSelCalStbd[9]:=(FALSE)'
_TEXTVARIABLES : '','','','',''
_COLORVARIABLES : '','','','','',''
_ACCESSLEVELS : 2,2,2,2,2,2,2,2
_OBJECT : 0,1
_THRESH2 : '','','',''
_INPUTTYPE : '','',''
_HIDDENINPUT : 0
_END_ELEM
(* @TEXTSCALINGVARS := '_TEXTSCALINGVARS: $'$',$'$'' *)
(* @EXTENDEDSIMPLESHAPE := '_SIMPLE: 0' *)
(* @INPUTTAPFALSE := '_INPUTTAPFALSE: 0' *)

_SIMPLE : 0
_LINEWIDTH : 0
_NOCOLORS : 0,1
_POS : 305,95,396,116,350,105
_COLORS : 12828343,8388608,16776960,16777215,0
_VARIABLES : '','','','','','','',''
_THRESH : '','','',''
_DSP : '','BOTTOM DEF.',''
_ZOOM : ''
_INPUT : 0
_TEXT : 5,4294967285,400,0,482,0,0,0
_FONT : 'MS Sans Serif'
_EXEC : ''
_TEXTVARIABLES : '','','','',''
_COLORVARIABLES : '','','','','',''
_ACCESSLEVELS : 2,2,2,2,2,2,2,2
_OBJECT : 0,0
_THRESH2 : '','','',''
_INPUTTYPE : '','',''
_HIDDENINPUT : 0
_END_ELEM
(* @TEXTSCALINGVARS := '_TEXTSCALINGVARS: $'$',$'$'' *)
(* @EXTENDEDSIMPLESHAPE := '_SIMPLE: 0' *)
(* @INPUTTAPFALSE := '_INPUTTAPFALSE: 0' *)

_SIMPLE : 0
_LINEWIDTH : 0
_NOCOLORS : 1,1
_POS : 305,285,396,306,350,295
_COLORS : 16777215,0,16777215,0,0
_VARIABLES : '','','','','','','',''
_THRESH : '','','',''
_DSP : 'PARAMS.stMastSetup.aBDef[4,3]','%.0f %% ',''
_ZOOM : ''
_INPUT : 1048576
_TEXT : 6,4294967283,400,0,483,0,0,0
_FONT : 'MS Sans Serif'
_EXEC : 'INTERN ASSIGN INPUTS.PresSelCalStbd[9]:=(FALSE)'
_TEXTVARIABLES : '','','','',''
_COLORVARIABLES : '','','','','',''
_ACCESSLEVELS : 2,2,2,2,2,2,2,2
_OBJECT : 0,1
_THRESH2 : '','','',''
_INPUTTYPE : '','',''
_HIDDENINPUT : 0
_END_ELEM
(* @TEXTSCALINGVARS := '_TEXTSCALINGVARS: $'$',$'$'' *)
(* @EXTENDEDSIMPLESHAPE := '_SIMPLE: 0' *)
(* @INPUTTAPFALSE := '_INPUTTAPFALSE: 0' *)

_SIMPLE : 0
_LINEWIDTH : 0
_NOCOLORS : 1,1
_POS : 305,325,396,346,350,335
_COLORS : 16777215,0,16777215,0,0
_VARIABLES : '','','','','','','',''
_THRESH : '','','',''
_DSP : 'PARAMS.stMastSetup.aBDef[2,3]','%.0f %% ',''
_ZOOM : ''
_INPUT : 1048576
_TEXT : 6,4294967283,400,0,484,0,0,0
_FONT : 'MS Sans Serif'
_EXEC : 'INTERN ASSIGN INPUTS.PresSelCalStbd[9]:=(FALSE)'
_TEXTVARIABLES : '','','','',''
_COLORVARIABLES : '','','','','',''
_ACCESSLEVELS : 2,2,2,2,2,2,2,2
_OBJECT : 0,1
_THRESH2 : '','','',''
_INPUTTYPE : '','',''
_HIDDENINPUT : 0
_END_ELEM
(* @TEXTSCALINGVARS := '_TEXTSCALINGVARS: $'$',$'$'' *)
(* @EXTENDEDSIMPLESHAPE := '_SIMPLE: 0' *)
(* @INPUTTAPFALSE := '_INPUTTAPFALSE: 0' *)

_SIMPLE : 0
_LINEWIDTH : 0
_NOCOLORS : 1,1
_POS : 305,305,396,326,350,315
_COLORS : 16777215,0,16777215,0,0
_VARIABLES : '','','','','','','',''
_THRESH : '','','',''
_DSP : 'PARAMS.stMastSetup.aBDef[1,3]','%.0f %% ',''
_ZOOM : ''
_INPUT : 1048576
_TEXT : 6,4294967283,400,0,485,0,0,0
_FONT : 'MS Sans Serif'
_EXEC : 'INTERN ASSIGN INPUTS.PresSelCalStbd[9]:=(FALSE)'
_TEXTVARIABLES : '','','','',''
_COLORVARIABLES : '','','','','',''
_ACCESSLEVELS : 2,2,2,2,2,2,2,2
_OBJECT : 0,1
_THRESH2 : '','','',''
_INPUTTYPE : '','',''
_HIDDENINPUT : 0
_END_ELEM
(* @TEXTSCALINGVARS := '_TEXTSCALINGVARS: $'$',$'$'' *)
(* @EXTENDEDSIMPLESHAPE := '_SIMPLE: 0' *)
(* @INPUTTAPFALSE := '_INPUTTAPFALSE: 0' *)

_SIMPLE : 0
_LINEWIDTH : 0
_NOCOLORS : 1,1
_POS : 305,350,396,371,350,360
_COLORS : 16777215,0,16777215,0,0
_VARIABLES : '','','','','','','',''
_THRESH : '','','',''
_DSP : 'PARAMS.stMastSetup.aBDef[4,4]','%.0f %% ',''
_ZOOM : ''
_INPUT : 1048576
_TEXT : 6,4294967283,400,0,486,0,0,0
_FONT : 'MS Sans Serif'
_EXEC : 'INTERN ASSIGN INPUTS.PresSelCalStbd[9]:=(FALSE)'
_TEXTVARIABLES : '','','','',''
_COLORVARIABLES : '','','','','',''
_ACCESSLEVELS : 2,2,2,2,2,2,2,2
_OBJECT : 0,1
_THRESH2 : '','','',''
_INPUTTYPE : '','',''
_HIDDENINPUT : 0
_END_ELEM
(* @TEXTSCALINGVARS := '_TEXTSCALINGVARS: $'$',$'$'' *)
(* @EXTENDEDSIMPLESHAPE := '_SIMPLE: 0' *)
(* @INPUTTAPFALSE := '_INPUTTAPFALSE: 0' *)

_SIMPLE : 0
_LINEWIDTH : 0
_NOCOLORS : 1,1
_POS : 305,390,396,411,350,400
_COLORS : 16777215,0,16777215,0,0
_VARIABLES : '','','','','','','',''
_THRESH : '','','',''
_DSP : 'PARAMS.stMastSetup.aBDef[2,4]','%.0f %% ',''
_ZOOM : ''
_INPUT : 1048576
_TEXT : 6,4294967283,400,0,487,0,0,0
_FONT : 'MS Sans Serif'
_EXEC : 'INTERN ASSIGN INPUTS.PresSelCalStbd[9]:=(FALSE)'
_TEXTVARIABLES : '','','','',''
_COLORVARIABLES : '','','','','',''
_ACCESSLEVELS : 2,2,2,2,2,2,2,2
_OBJECT : 0,1
_THRESH2 : '','','',''
_INPUTTYPE : '','',''
_HIDDENINPUT : 0
_END_ELEM
(* @TEXTSCALINGVARS := '_TEXTSCALINGVARS: $'$',$'$'' *)
(* @EXTENDEDSIMPLESHAPE := '_SIMPLE: 0' *)
(* @INPUTTAPFALSE := '_INPUTTAPFALSE: 0' *)

_SIMPLE : 0
_LINEWIDTH : 0
_NOCOLORS : 1,1
_POS : 305,370,396,391,350,380
_COLORS : 16777215,0,16777215,0,0
_VARIABLES : '','','','','','','',''
_THRESH : '','','',''
_DSP : 'PARAMS.stMastSetup.aBDef[1,4]','%.0f %% ',''
_ZOOM : ''
_INPUT : 1048576
_TEXT : 6,4294967283,400,0,488,0,0,0
_FONT : 'MS Sans Serif'
_EXEC : 'INTERN ASSIGN INPUTS.PresSelCalStbd[9]:=(FALSE)'
_TEXTVARIABLES : '','','','',''
_COLORVARIABLES : '','','','','',''
_ACCESSLEVELS : 2,2,2,2,2,2,2,2
_OBJECT : 0,1
_THRESH2 : '','','',''
_INPUTTYPE : '','',''
_HIDDENINPUT : 0
_END_ELEM
(* @TEXTSCALINGVARS := '_TEXTSCALINGVARS: $'$',$'$'' *)
(* @EXTENDEDSIMPLESHAPE := '_SIMPLE: 0' *)
(* @INPUTTAPFALSE := '_INPUTTAPFALSE: 0' *)

_SIMPLE : 0
_LINEWIDTH : 0
_NOCOLORS : 1,1
_POS : 305,410,396,431,350,420
_COLORS : 16777215,0,16777215,0,0
_VARIABLES : '','','','','','','',''
_THRESH : '','','',''
_DSP : 'PARAMS.stMastSetup.aBDef[3,4]','%.0f %% ',''
_ZOOM : ''
_INPUT : 1048576
_TEXT : 6,4294967283,400,0,489,0,0,0
_FONT : 'MS Sans Serif'
_EXEC : 'INTERN ASSIGN INPUTS.PresSelCalStbd[9]:=(FALSE)'
_TEXTVARIABLES : '','','','',''
_COLORVARIABLES : '','','','','',''
_ACCESSLEVELS : 2,2,2,2,2,2,2,2
_OBJECT : 0,1
_THRESH2 : '','','',''
_INPUTTYPE : '','',''
_HIDDENINPUT : 0
_END_ELEM
(* @TEXTSCALINGVARS := '_TEXTSCALINGVARS: $'$',$'$'' *)
(* @EXTENDEDSIMPLESHAPE := '_SIMPLE: 0' *)
(* @INPUTTAPFALSE := '_INPUTTAPFALSE: 0' *)

_SIMPLE : 0
_LINEWIDTH : 0
_NOCOLORS : 1,1
_POS : 400,115,491,136,445,125
_COLORS : 16777215,0,16777215,0,0
_VARIABLES : '','','','','','','',''
_THRESH : '','','',''
_DSP : 'PARAMS.stMastSetup.aFSY[4,1]','%.0f %% ',''
_ZOOM : ''
_INPUT : 1048576
_TEXT : 6,4294967283,400,0,490,0,0,0
_FONT : 'MS Sans Serif'
_EXEC : 'INTERN ASSIGN INPUTS.PresSelCalStbd[9]:=(FALSE)'
_TEXTVARIABLES : '','','','',''
_COLORVARIABLES : '','','','','',''
_ACCESSLEVELS : 2,2,2,2,2,2,2,2
_OBJECT : 0,1
_THRESH2 : '','','',''
_INPUTTYPE : '','',''
_HIDDENINPUT : 0
_END_ELEM
(* @TEXTSCALINGVARS := '_TEXTSCALINGVARS: $'$',$'$'' *)
(* @EXTENDEDSIMPLESHAPE := '_SIMPLE: 0' *)
(* @INPUTTAPFALSE := '_INPUTTAPFALSE: 0' *)

_SIMPLE : 0
_LINEWIDTH : 0
_NOCOLORS : 1,1
_POS : 400,135,491,156,445,145
_COLORS : 16777215,0,16777215,0,0
_VARIABLES : '','','','','','','',''
_THRESH : '','','',''
_DSP : 'PARAMS.stMastSetup.aFSY[4,5]','%.0f %% ',''
_ZOOM : ''
_INPUT : 1048576
_TEXT : 6,4294967283,400,0,491,0,0,0
_FONT : 'MS Sans Serif'
_EXEC : 'INTERN ASSIGN INPUTS.PresSelCalStbd[9]:=(FALSE)'
_TEXTVARIABLES : '','','','',''
_COLORVARIABLES : '','','','','',''
_ACCESSLEVELS : 2,2,2,2,2,2,2,2
_OBJECT : 0,1
_THRESH2 : '','','',''
_INPUTTYPE : '','',''
_HIDDENINPUT : 0
_END_ELEM
(* @TEXTSCALINGVARS := '_TEXTSCALINGVARS: $'$',$'$'' *)
(* @EXTENDEDSIMPLESHAPE := '_SIMPLE: 0' *)
(* @INPUTTAPFALSE := '_INPUTTAPFALSE: 0' *)

_SIMPLE : 0
_LINEWIDTH : 0
_NOCOLORS : 1,1
_POS : 400,180,491,201,445,190
_COLORS : 16777215,0,16777215,0,0
_VARIABLES : '','','','','','','',''
_THRESH : '','','',''
_DSP : 'PARAMS.stMastSetup.aFSY[4,2]','%.0f %% ',''
_ZOOM : ''
_INPUT : 1048576
_TEXT : 6,4294967283,400,0,492,0,0,0
_FONT : 'MS Sans Serif'
_EXEC : 'INTERN ASSIGN INPUTS.PresSelCalStbd[9]:=(FALSE)'
_TEXTVARIABLES : '','','','',''
_COLORVARIABLES : '','','','','',''
_ACCESSLEVELS : 2,2,2,2,2,2,2,2
_OBJECT : 0,1
_THRESH2 : '','','',''
_INPUTTYPE : '','',''
_HIDDENINPUT : 0
_END_ELEM
(* @TEXTSCALINGVARS := '_TEXTSCALINGVARS: $'$',$'$'' *)
(* @EXTENDEDSIMPLESHAPE := '_SIMPLE: 0' *)
(* @INPUTTAPFALSE := '_INPUTTAPFALSE: 0' *)

_SIMPLE : 0
_LINEWIDTH : 0
_NOCOLORS : 1,1
_POS : 400,200,491,221,445,210
_COLORS : 16777215,0,16777215,0,0
_VARIABLES : '','','','','','','',''
_THRESH : '','','',''
_DSP : 'PARAMS.stMastSetup.aFSY[4,6]','%.0f %% ',''
_ZOOM : ''
_INPUT : 1048576
_TEXT : 6,4294967283,400,0,493,0,0,0
_FONT : 'MS Sans Serif'
_EXEC : 'INTERN ASSIGN INPUTS.PresSelCalStbd[9]:=(FALSE)'
_TEXTVARIABLES : '','','','',''
_COLORVARIABLES : '','','','','',''
_ACCESSLEVELS : 2,2,2,2,2,2,2,2
_OBJECT : 0,1
_THRESH2 : '','','',''
_INPUTTYPE : '','',''
_HIDDENINPUT : 0
_END_ELEM
(* @TEXTSCALINGVARS := '_TEXTSCALINGVARS: $'$',$'$'' *)
(* @EXTENDEDSIMPLESHAPE := '_SIMPLE: 0' *)
(* @INPUTTAPFALSE := '_INPUTTAPFALSE: 0' *)

_SIMPLE : 0
_LINEWIDTH : 0
_NOCOLORS : 1,1
_POS : 400,240,491,261,445,250
_COLORS : 16777215,0,16777215,0,0
_VARIABLES : '','','','','','','',''
_THRESH : '','','',''
_DSP : 'PARAMS.stMastSetup.aFSY[1,6]','%.0f %% ',''
_ZOOM : ''
_INPUT : 1048576
_TEXT : 6,4294967283,400,0,494,0,0,0
_FONT : 'MS Sans Serif'
_EXEC : 'INTERN ASSIGN INPUTS.PresSelCalStbd[9]:=(FALSE)'
_TEXTVARIABLES : '','','','',''
_COLORVARIABLES : '','','','','',''
_ACCESSLEVELS : 2,2,2,2,2,2,2,2
_OBJECT : 0,1
_THRESH2 : '','','',''
_INPUTTYPE : '','',''
_HIDDENINPUT : 0
_END_ELEM
(* @TEXTSCALINGVARS := '_TEXTSCALINGVARS: $'$',$'$'' *)
(* @EXTENDEDSIMPLESHAPE := '_SIMPLE: 0' *)
(* @INPUTTAPFALSE := '_INPUTTAPFALSE: 0' *)

_SIMPLE : 0
_LINEWIDTH : 0
_NOCOLORS : 1,1
_POS : 400,260,491,281,445,270
_COLORS : 16777215,0,16777215,0,0
_VARIABLES : '','','','','','','',''
_THRESH : '','','',''
_DSP : 'PARAMS.stMastSetup.aFSY[2,2]','%.0f %% ',''
_ZOOM : ''
_INPUT : 1048576
_TEXT : 6,4294967283,400,0,495,0,0,0
_FONT : 'MS Sans Serif'
_EXEC : 'INTERN ASSIGN INPUTS.PresSelCalStbd[9]:=(FALSE)'
_TEXTVARIABLES : '','','','',''
_COLORVARIABLES : '','','','','',''
_ACCESSLEVELS : 2,2,2,2,2,2,2,2
_OBJECT : 0,1
_THRESH2 : '','','',''
_INPUTTYPE : '','',''
_HIDDENINPUT : 0
_END_ELEM
(* @TEXTSCALINGVARS := '_TEXTSCALINGVARS: $'$',$'$'' *)
(* @EXTENDEDSIMPLESHAPE := '_SIMPLE: 0' *)
(* @INPUTTAPFALSE := '_INPUTTAPFALSE: 0' *)

_SIMPLE : 0
_LINEWIDTH : 0
_NOCOLORS : 1,1
_POS : 400,155,491,176,445,165
_COLORS : 16777215,0,16777215,0,0
_VARIABLES : '','','','','','','',''
_THRESH : '','','',''
_DSP : 'PARAMS.stMastSetup.aFSY[1,1]','%.0f %% ',''
_ZOOM : ''
_INPUT : 1048576
_TEXT : 6,4294967283,400,0,496,0,0,0
_FONT : 'MS Sans Serif'
_EXEC : 'INTERN ASSIGN INPUTS.PresSelCalStbd[9]:=(FALSE)'
_TEXTVARIABLES : '','','','',''
_COLORVARIABLES : '','','','','',''
_ACCESSLEVELS : 2,2,2,2,2,2,2,2
_OBJECT : 0,1
_THRESH2 : '','','',''
_INPUTTYPE : '','',''
_HIDDENINPUT : 0
_END_ELEM
(* @TEXTSCALINGVARS := '_TEXTSCALINGVARS: $'$',$'$'' *)
(* @EXTENDEDSIMPLESHAPE := '_SIMPLE: 0' *)
(* @INPUTTAPFALSE := '_INPUTTAPFALSE: 0' *)

_SIMPLE : 0
_LINEWIDTH : 0
_NOCOLORS : 1,1
_POS : 400,220,491,241,445,230
_COLORS : 16777215,0,16777215,0,0
_VARIABLES : '','','','','','','',''
_THRESH : '','','',''
_DSP : 'PARAMS.stMastSetup.aFSY[1,2]','%.0f %% ',''
_ZOOM : ''
_INPUT : 1048576
_TEXT : 6,4294967283,400,0,497,0,0,0
_FONT : 'MS Sans Serif'
_EXEC : 'INTERN ASSIGN INPUTS.PresSelCalStbd[9]:=(FALSE)'
_TEXTVARIABLES : '','','','',''
_COLORVARIABLES : '','','','','',''
_ACCESSLEVELS : 2,2,2,2,2,2,2,2
_OBJECT : 0,1
_THRESH2 : '','','',''
_INPUTTYPE : '','',''
_HIDDENINPUT : 0
_END_ELEM
(* @TEXTSCALINGVARS := '_TEXTSCALINGVARS: $'$',$'$'' *)
(* @EXTENDEDSIMPLESHAPE := '_SIMPLE: 0' *)
(* @INPUTTAPFALSE := '_INPUTTAPFALSE: 0' *)

_SIMPLE : 0
_LINEWIDTH : 0
_NOCOLORS : 0,1
_POS : 400,95,491,116,445,105
_COLORS : 12828343,8388608,16776960,16777215,0
_VARIABLES : '','','','','','','',''
_THRESH : '','','',''
_DSP : '','FORESTAY',''
_ZOOM : ''
_INPUT : 0
_TEXT : 5,4294967285,400,0,498,0,0,0
_FONT : 'MS Sans Serif'
_EXEC : ''
_TEXTVARIABLES : '','','','',''
_COLORVARIABLES : '','','','','',''
_ACCESSLEVELS : 2,2,2,2,2,2,2,2
_OBJECT : 0,0
_THRESH2 : '','','',''
_INPUTTYPE : '','',''
_HIDDENINPUT : 0
_END_ELEM
(* @TEXTSCALINGVARS := '_TEXTSCALINGVARS: $'$',$'$'' *)
(* @EXTENDEDSIMPLESHAPE := '_SIMPLE: 0' *)
(* @INPUTTAPFALSE := '_INPUTTAPFALSE: 0' *)

_SIMPLE : 0
_LINEWIDTH : 0
_NOCOLORS : 1,1
_POS : 400,285,491,306,445,295
_COLORS : 16777215,0,16777215,0,0
_VARIABLES : '','','','','','','',''
_THRESH : '','','',''
_DSP : 'PARAMS.stMastSetup.aFSY[4,3]','%.0f %% ',''
_ZOOM : ''
_INPUT : 1048576
_TEXT : 6,4294967283,400,0,499,0,0,0
_FONT : 'MS Sans Serif'
_EXEC : 'INTERN ASSIGN INPUTS.PresSelCalStbd[9]:=(FALSE)'
_TEXTVARIABLES : '','','','',''
_COLORVARIABLES : '','','','','',''
_ACCESSLEVELS : 2,2,2,2,2,2,2,2
_OBJECT : 0,1
_THRESH2 : '','','',''
_INPUTTYPE : '','',''
_HIDDENINPUT : 0
_END_ELEM
(* @TEXTSCALINGVARS := '_TEXTSCALINGVARS: $'$',$'$'' *)
(* @EXTENDEDSIMPLESHAPE := '_SIMPLE: 0' *)
(* @INPUTTAPFALSE := '_INPUTTAPFALSE: 0' *)

_SIMPLE : 0
_LINEWIDTH : 0
_NOCOLORS : 1,1
_POS : 400,325,491,346,445,335
_COLORS : 16777215,0,16777215,0,0
_VARIABLES : '','','','','','','',''
_THRESH : '','','',''
_DSP : 'PARAMS.stMastSetup.aFSY[2,3]','%.0f %% ',''
_ZOOM : ''
_INPUT : 1048576
_TEXT : 6,4294967283,400,0,500,0,0,0
_FONT : 'MS Sans Serif'
_EXEC : 'INTERN ASSIGN INPUTS.PresSelCalStbd[9]:=(FALSE)'
_TEXTVARIABLES : '','','','',''
_COLORVARIABLES : '','','','','',''
_ACCESSLEVELS : 2,2,2,2,2,2,2,2
_OBJECT : 0,1
_THRESH2 : '','','',''
_INPUTTYPE : '','',''
_HIDDENINPUT : 0
_END_ELEM
(* @TEXTSCALINGVARS := '_TEXTSCALINGVARS: $'$',$'$'' *)
(* @EXTENDEDSIMPLESHAPE := '_SIMPLE: 0' *)
(* @INPUTTAPFALSE := '_INPUTTAPFALSE: 0' *)

_SIMPLE : 0
_LINEWIDTH : 0
_NOCOLORS : 1,1
_POS : 400,305,491,326,445,315
_COLORS : 16777215,0,16777215,0,0
_VARIABLES : '','','','','','','',''
_THRESH : '','','',''
_DSP : 'PARAMS.stMastSetup.aFSY[1,3]','%.0f %% ',''
_ZOOM : ''
_INPUT : 1048576
_TEXT : 6,4294967283,400,0,501,0,0,0
_FONT : 'MS Sans Serif'
_EXEC : 'INTERN ASSIGN INPUTS.PresSelCalStbd[9]:=(FALSE)'
_TEXTVARIABLES : '','','','',''
_COLORVARIABLES : '','','','','',''
_ACCESSLEVELS : 2,2,2,2,2,2,2,2
_OBJECT : 0,1
_THRESH2 : '','','',''
_INPUTTYPE : '','',''
_HIDDENINPUT : 0
_END_ELEM
(* @TEXTSCALINGVARS := '_TEXTSCALINGVARS: $'$',$'$'' *)
(* @EXTENDEDSIMPLESHAPE := '_SIMPLE: 0' *)
(* @INPUTTAPFALSE := '_INPUTTAPFALSE: 0' *)

_SIMPLE : 0
_LINEWIDTH : 0
_NOCOLORS : 1,1
_POS : 400,350,491,371,445,360
_COLORS : 16777215,0,16777215,0,0
_VARIABLES : '','','','','','','',''
_THRESH : '','','',''
_DSP : 'PARAMS.stMastSetup.aFSY[4,4]','%.0f %% ',''
_ZOOM : ''
_INPUT : 1048576
_TEXT : 6,4294967283,400,0,502,0,0,0
_FONT : 'MS Sans Serif'
_EXEC : 'INTERN ASSIGN INPUTS.PresSelCalStbd[9]:=(FALSE)'
_TEXTVARIABLES : '','','','',''
_COLORVARIABLES : '','','','','',''
_ACCESSLEVELS : 2,2,2,2,2,2,2,2
_OBJECT : 0,1
_THRESH2 : '','','',''
_INPUTTYPE : '','',''
_HIDDENINPUT : 0
_END_ELEM
(* @TEXTSCALINGVARS := '_TEXTSCALINGVARS: $'$',$'$'' *)
(* @EXTENDEDSIMPLESHAPE := '_SIMPLE: 0' *)
(* @INPUTTAPFALSE := '_INPUTTAPFALSE: 0' *)

_SIMPLE : 0
_LINEWIDTH : 0
_NOCOLORS : 1,1
_POS : 400,390,491,411,445,400
_COLORS : 16777215,0,16777215,0,0
_VARIABLES : '','','','','','','',''
_THRESH : '','','',''
_DSP : 'PARAMS.stMastSetup.aFSY[2,4]','%.0f %% ',''
_ZOOM : ''
_INPUT : 1048576
_TEXT : 6,4294967283,400,0,503,0,0,0
_FONT : 'MS Sans Serif'
_EXEC : 'INTERN ASSIGN INPUTS.PresSelCalStbd[9]:=(FALSE)'
_TEXTVARIABLES : '','','','',''
_COLORVARIABLES : '','','','','',''
_ACCESSLEVELS : 2,2,2,2,2,2,2,2
_OBJECT : 0,1
_THRESH2 : '','','',''
_INPUTTYPE : '','',''
_HIDDENINPUT : 0
_END_ELEM
(* @TEXTSCALINGVARS := '_TEXTSCALINGVARS: $'$',$'$'' *)
(* @EXTENDEDSIMPLESHAPE := '_SIMPLE: 0' *)
(* @INPUTTAPFALSE := '_INPUTTAPFALSE: 0' *)

_SIMPLE : 0
_LINEWIDTH : 0
_NOCOLORS : 1,1
_POS : 400,370,491,391,445,380
_COLORS : 16777215,0,16777215,0,0
_VARIABLES : '','','','','','','',''
_THRESH : '','','',''
_DSP : 'PARAMS.stMastSetup.aFSY[1,4]','%.0f %% ',''
_ZOOM : ''
_INPUT : 1048576
_TEXT : 6,4294967283,400,0,504,0,0,0
_FONT : 'MS Sans Serif'
_EXEC : 'INTERN ASSIGN INPUTS.PresSelCalStbd[9]:=(FALSE)'
_TEXTVARIABLES : '','','','',''
_COLORVARIABLES : '','','','','',''
_ACCESSLEVELS : 2,2,2,2,2,2,2,2
_OBJECT : 0,1
_THRESH2 : '','','',''
_INPUTTYPE : '','',''
_HIDDENINPUT : 0
_END_ELEM
(* @TEXTSCALINGVARS := '_TEXTSCALINGVARS: $'$',$'$'' *)
(* @EXTENDEDSIMPLESHAPE := '_SIMPLE: 0' *)
(* @INPUTTAPFALSE := '_INPUTTAPFALSE: 0' *)

_SIMPLE : 0
_LINEWIDTH : 0
_NOCOLORS : 1,1
_POS : 400,410,491,431,445,420
_COLORS : 16777215,0,16777215,0,0
_VARIABLES : '','','','','','','',''
_THRESH : '','','',''
_DSP : 'PARAMS.stMastSetup.aFSY[3,4]','%.0f %% ',''
_ZOOM : ''
_INPUT : 1048576
_TEXT : 6,4294967283,400,0,505,0,0,0
_FONT : 'MS Sans Serif'
_EXEC : 'INTERN ASSIGN INPUTS.PresSelCalStbd[9]:=(FALSE)'
_TEXTVARIABLES : '','','','',''
_COLORVARIABLES : '','','','','',''
_ACCESSLEVELS : 2,2,2,2,2,2,2,2
_OBJECT : 0,1
_THRESH2 : '','','',''
_INPUTTYPE : '','',''
_HIDDENINPUT : 0
_END_ELEM
(* @TEXTSCALINGVARS := '_TEXTSCALINGVARS: $'$',$'$'' *)
(* @EXTENDEDSIMPLESHAPE := '_SIMPLE: 0' *)
(* @INPUTTAPFALSE := '_INPUTTAPFALSE: 0' *)
_KEYINFOLIST : 0
END_VISUALISATION
