(* @PATH := '' *)

VISUALISATION VISU_1_TANK _VISU_TYPES : 1,1
_BG_BMP : 'visu_tank.bmp'
_TEXT : 95
_PAINTZOOM : 100

_SIMPLE : 0
_LINEWIDTH : 0
_NOCOLORS : 0,0
_POS : 20,0,331,51,175,25
_COLORS : 16777215,0,16777215,0,16777215
_VARIABLES : '','','','','','','',''
_THRESH : '','','',''
_DSP : '','TANK',''
_ZOOM : ''
_INPUT : 0
_TEXT : 4,4294967264,700,0,0,0,0,0
_FONT : 'MS Sans Serif'
_EXEC : ''
_TEXTVARIABLES : '','','','',''
_COLORVARIABLES : '','','','','',''
_ACCESSLEVELS : 2,2,2,2,2,2,2,2
_OBJECT : 0,0
_THRESH2 : '','','',''
_INPUTTYPE : '','',''
_HIDDENINPUT : 0
_END_ELEM
(* @TEXTSCALINGVARS := '_TEXTSCALINGVARS: $'$',$'$'' *)
(* @EXTENDEDSIMPLESHAPE := '_SIMPLE: 0' *)
(* @INPUTTAPFALSE := '_INPUTTAPFALSE: 0' *)

_SIMPLE : 0
_LINEWIDTH : 0
_NOCOLORS : 1,1
_POS : 410,380,506,406,458,393
_COLORS : 12632256,0,8421631,0,0
_VARIABLES : '','','','','','','',''
_THRESH : '','P010.Alarm.Adver','',''
_DSP : 'P010.Bar','P010: %.1f bar',''
_ZOOM : ''
_INPUT : 0
_TEXT : 5,4294967285,700,0,15,0,0,0
_FONT : 'MS Sans Serif'
_EXEC : ''
_TEXTVARIABLES : '','','','',''
_COLORVARIABLES : '','','','','',''
_ACCESSLEVELS : 2,2,2,2,2,2,2,2
_OBJECT : 0,0
_THRESH2 : '','','',''
_INPUTTYPE : '','',''
_HIDDENINPUT : 0
_END_ELEM
(* @TEXTSCALINGVARS := '_TEXTSCALINGVARS: $'$',$'$'' *)
(* @EXTENDEDSIMPLESHAPE := '_SIMPLE: 0' *)
(* @INPUTTAPFALSE := '_INPUTTAPFALSE: 0' *)

_SIMPLE : 2
_LINEWIDTH : 0
_NOCOLORS : 1,1
_POS : 215,140,266,166,240,153
_COLORS : 8454016,0,8421631,0,0
_VARIABLES : '','','','','','','',''
_THRESH : '','SF004.Alarm.Adver','',''
_DSP : '','SF004',''
_ZOOM : ''
_INPUT : 0
_TEXT : 5,4294967284,400,0,20,0,0,0
_FONT : ''
_EXEC : ''
_TEXTVARIABLES : '','','','',''
_COLORVARIABLES : '','','','','',''
_ACCESSLEVELS : 2,2,2,2,2,2,2,2
_OBJECT : 0,0
_THRESH2 : '','','',''
_INPUTTYPE : '','',''
_HIDDENINPUT : 0
_END_ELEM
(* @TEXTSCALINGVARS := '_TEXTSCALINGVARS: $'$',$'$'' *)
(* @EXTENDEDSIMPLESHAPE := '_SIMPLE: 0' *)
(* @INPUTTAPFALSE := '_INPUTTAPFALSE: 0' *)

_SIMPLE : 2
_LINEWIDTH : 0
_NOCOLORS : 1,1
_POS : 455,160,506,186,480,173
_COLORS : 8454016,0,8421631,0,0
_VARIABLES : '','','','','','','',''
_THRESH : '','SF002.Alarm.Adver','',''
_DSP : '','SF002',''
_ZOOM : ''
_INPUT : 0
_TEXT : 5,4294967284,400,0,24,0,0,0
_FONT : ''
_EXEC : ''
_TEXTVARIABLES : '','','','',''
_COLORVARIABLES : '','','','','',''
_ACCESSLEVELS : 2,2,2,2,2,2,2,2
_OBJECT : 0,0
_THRESH2 : '','','',''
_INPUTTYPE : '','',''
_HIDDENINPUT : 0
_END_ELEM
(* @TEXTSCALINGVARS := '_TEXTSCALINGVARS: $'$',$'$'' *)
(* @EXTENDEDSIMPLESHAPE := '_SIMPLE: 0' *)
(* @INPUTTAPFALSE := '_INPUTTAPFALSE: 0' *)

_SIMPLE : 1
_LINEWIDTH : 0
_NOCOLORS : 1,1
_POS : 510,160,561,186,535,173
_COLORS : 8454143,0,33023,0,0
_VARIABLES : '','','','','','','',''
_THRESH : '','TANK.SF002_Mute','TANK.SF002_Mute',''
_DSP : '','MUTE',''
_ZOOM : ''
_INPUT : 65536
_TEXT : 5,4294967284,400,0,26,0,0,0
_FONT : ''
_EXEC : ''
_TEXTVARIABLES : '','','','',''
_COLORVARIABLES : '','','','','',''
_ACCESSLEVELS : 2,2,2,2,2,2,2,2
_OBJECT : 0,0
_THRESH2 : '','','',''
_INPUTTYPE : '','',''
_HIDDENINPUT : 0
_END_ELEM
(* @TEXTSCALINGVARS := '_TEXTSCALINGVARS: $'$',$'$'' *)
(* @EXTENDEDSIMPLESHAPE := '_SIMPLE: 0' *)
(* @INPUTTAPFALSE := '_INPUTTAPFALSE: 0' *)

_SIMPLE : 1
_LINEWIDTH : 0
_NOCOLORS : 1,1
_POS : 510,380,561,406,535,393
_COLORS : 8454143,0,33023,0,0
_VARIABLES : '','','','','','','',''
_THRESH : '','TANK.P010_Mute','TANK.P010_Mute',''
_DSP : '','MUTE',''
_ZOOM : ''
_INPUT : 65536
_TEXT : 5,4294967284,400,0,27,0,0,0
_FONT : ''
_EXEC : ''
_TEXTVARIABLES : '','','','',''
_COLORVARIABLES : '','','','','',''
_ACCESSLEVELS : 2,2,2,2,2,2,2,2
_OBJECT : 0,0
_THRESH2 : '','','',''
_INPUTTYPE : '','',''
_HIDDENINPUT : 0
_END_ELEM
(* @TEXTSCALINGVARS := '_TEXTSCALINGVARS: $'$',$'$'' *)
(* @EXTENDEDSIMPLESHAPE := '_SIMPLE: 0' *)
(* @INPUTTAPFALSE := '_INPUTTAPFALSE: 0' *)

_SIMPLE : 1
_LINEWIDTH : 0
_NOCOLORS : 1,1
_POS : 900,500,1021,551,960,525
_COLORS : 16777215,0,16777215,0,0
_VARIABLES : '','','','','','','',''
_THRESH : '','','',''
_DSP : '','',''
_ZOOM : ''
_INPUT : 0
_TEXT : 5,4294967284,400,0,52,0,0,0
_FONT : ''
_EXEC : ''
_TEXTVARIABLES : '','','','',''
_COLORVARIABLES : '','','','','',''
_ACCESSLEVELS : 2,2,2,2,2,2,2,2
_OBJECT : 0,0
_THRESH2 : '','','',''
_INPUTTYPE : '','',''
_HIDDENINPUT : 0
_END_ELEM
(* @TEXTSCALINGVARS := '_TEXTSCALINGVARS: $'$',$'$'' *)
(* @EXTENDEDSIMPLESHAPE := '_SIMPLE: 0' *)
(* @INPUTTAPFALSE := '_INPUTTAPFALSE: 0' *)

_SIMPLE : 1
_LINEWIDTH : 0
_NOCOLORS : 1,1
_POS : 905,505,1016,546,960,525
_COLORS : 2105379,0,16777215,0,16777215
_VARIABLES : '','','','','','','',''
_THRESH : '','','',''
_DSP : '','RETURN',''
_ZOOM : 'VISU_0_MAIN'
_INPUT : 262144
_TEXT : 5,4294967283,700,0,53,0,0,0
_FONT : 'MS Sans Serif'
_EXEC : ''
_TEXTVARIABLES : '','','','',''
_COLORVARIABLES : '','','','','',''
_ACCESSLEVELS : 2,2,2,2,2,2,2,2
_OBJECT : 0,0
_THRESH2 : '','','',''
_INPUTTYPE : '','',''
_HIDDENINPUT : 0
_END_ELEM
(* @TEXTSCALINGVARS := '_TEXTSCALINGVARS: $'$',$'$'' *)
(* @EXTENDEDSIMPLESHAPE := '_SIMPLE: 0' *)
(* @INPUTTAPFALSE := '_INPUTTAPFALSE: 0' *)

_SIMPLE : 0
_LINEWIDTH : 0
_NOCOLORS : 0,0
_POS : 20,550,331,601,175,575
_COLORS : 16777215,0,16777215,0,16777215
_VARIABLES : '','','','','','','',''
_THRESH : '','','',''
_DSP : 'INPUTS.sVisuTime','%s',''
_ZOOM : ''
_INPUT : 0
_TEXT : 4,4294967264,700,0,54,0,0,0
_FONT : 'MS Sans Serif'
_EXEC : ''
_TEXTVARIABLES : '','','','',''
_COLORVARIABLES : '','','','','',''
_ACCESSLEVELS : 2,2,2,2,2,2,2,2
_OBJECT : 0,0
_THRESH2 : '','','',''
_INPUTTYPE : '','',''
_HIDDENINPUT : 0
_END_ELEM
(* @TEXTSCALINGVARS := '_TEXTSCALINGVARS: $'$',$'$'' *)
(* @EXTENDEDSIMPLESHAPE := '_SIMPLE: 0' *)
(* @INPUTTAPFALSE := '_INPUTTAPFALSE: 0' *)

_SIMPLE : 1
_LINEWIDTH : 0
_NOCOLORS : 1,1
_POS : 900,50,1021,101,960,75
_COLORS : 255,0,16777215,0,0
_VARIABLES : '','','','','','','',''
_THRESH : '','MAIN.aSys_Enable[1]','',''
_DSP : '','',''
_ZOOM : ''
_INPUT : 0
_TEXT : 5,4294967284,400,0,55,0,0,0
_FONT : ''
_EXEC : ''
_TEXTVARIABLES : '','','','',''
_COLORVARIABLES : '','','','','',''
_ACCESSLEVELS : 2,2,2,2,2,2,2,2
_OBJECT : 0,0
_THRESH2 : '','','',''
_INPUTTYPE : '','',''
_HIDDENINPUT : 0
_END_ELEM
(* @TEXTSCALINGVARS := '_TEXTSCALINGVARS: $'$',$'$'' *)
(* @EXTENDEDSIMPLESHAPE := '_SIMPLE: 0' *)
(* @INPUTTAPFALSE := '_INPUTTAPFALSE: 0' *)

_SIMPLE : 1
_LINEWIDTH : 0
_NOCOLORS : 1,1
_POS : 905,55,1016,96,960,75
_COLORS : 8421631,0,8454016,0,0
_VARIABLES : '','','','','','','',''
_THRESH : '','MAIN.aSys_Enable[1]','','MAIN.SITankEnable.In'
_DSP : '','ENABLE',''
_ZOOM : ''
_INPUT : 131072
_TEXT : 5,4294967283,700,0,56,0,0,0
_FONT : 'MS Sans Serif'
_EXEC : ''
_TEXTVARIABLES : '','','','',''
_COLORVARIABLES : '','','','','',''
_ACCESSLEVELS : 2,2,2,2,2,2,2,2
_OBJECT : 0,0
_THRESH2 : '','','',''
_INPUTTYPE : '','',''
_HIDDENINPUT : 0
_END_ELEM
(* @TEXTSCALINGVARS := '_TEXTSCALINGVARS: $'$',$'$'' *)
(* @EXTENDEDSIMPLESHAPE := '_SIMPLE: 0' *)
(* @INPUTTAPFALSE := '_INPUTTAPFALSE: 0' *)

_SIMPLE : 1
_LINEWIDTH : 0
_NOCOLORS : 1,1
_POS : 900,445,1021,496,960,470
_COLORS : 16777215,0,16777215,0,0
_VARIABLES : '','','','','','','',''
_THRESH : '','','',''
_DSP : '','',''
_ZOOM : ''
_INPUT : 0
_TEXT : 5,4294967284,400,0,57,0,0,0
_FONT : ''
_EXEC : ''
_TEXTVARIABLES : '','','','',''
_COLORVARIABLES : '','','','','',''
_ACCESSLEVELS : 2,2,2,2,2,2,2,2
_OBJECT : 0,0
_THRESH2 : '','','',''
_INPUTTYPE : '','',''
_HIDDENINPUT : 0
_END_ELEM
(* @TEXTSCALINGVARS := '_TEXTSCALINGVARS: $'$',$'$'' *)
(* @EXTENDEDSIMPLESHAPE := '_SIMPLE: 0' *)
(* @INPUTTAPFALSE := '_INPUTTAPFALSE: 0' *)

_SIMPLE : 1
_LINEWIDTH : 0
_NOCOLORS : 1,1
_POS : 905,450,1016,491,960,470
_COLORS : 8421504,0,16777215,0,16777215
_VARIABLES : '','','','','','','',''
_THRESH : '','','',''
_DSP : '','CONFIG:$R$NTANK',''
_ZOOM : 'VISU_CFG_TANK'
_INPUT : 262144
_TEXT : 5,4294967283,700,0,58,0,0,0
_FONT : 'MS Sans Serif'
_EXEC : ''
_TEXTVARIABLES : '','','','',''
_COLORVARIABLES : '','','','','',''
_ACCESSLEVELS : 2,2,2,2,2,2,2,2
_OBJECT : 0,0
_THRESH2 : '','','',''
_INPUTTYPE : '','',''
_HIDDENINPUT : 0
_END_ELEM
(* @TEXTSCALINGVARS := '_TEXTSCALINGVARS: $'$',$'$'' *)
(* @EXTENDEDSIMPLESHAPE := '_SIMPLE: 0' *)
(* @INPUTTAPFALSE := '_INPUTTAPFALSE: 0' *)

_SIMPLE : 2
_LINEWIDTH : 0
_NOCOLORS : 1,1
_POS : 170,205,221,231,195,218
_COLORS : 8454016,0,8421631,0,0
_VARIABLES : '','','','','','','',''
_THRESH : '','SF006.Alarm.Adver','',''
_DSP : '','SF006',''
_ZOOM : ''
_INPUT : 0
_TEXT : 5,4294967284,400,0,66,0,0,0
_FONT : ''
_EXEC : ''
_TEXTVARIABLES : '','','','',''
_COLORVARIABLES : '','','','','',''
_ACCESSLEVELS : 2,2,2,2,2,2,2,2
_OBJECT : 0,0
_THRESH2 : '','','',''
_INPUTTYPE : '','',''
_HIDDENINPUT : 0
_END_ELEM
(* @TEXTSCALINGVARS := '_TEXTSCALINGVARS: $'$',$'$'' *)
(* @EXTENDEDSIMPLESHAPE := '_SIMPLE: 0' *)
(* @INPUTTAPFALSE := '_INPUTTAPFALSE: 0' *)

_SIMPLE : 2
_LINEWIDTH : 0
_NOCOLORS : 1,1
_POS : 185,430,236,456,210,443
_COLORS : 8454016,0,8421631,0,0
_VARIABLES : '','','','','','','',''
_THRESH : '','SF008.Alarm.Adver','',''
_DSP : '','SF008',''
_ZOOM : ''
_INPUT : 0
_TEXT : 5,4294967284,400,0,68,0,0,0
_FONT : ''
_EXEC : ''
_TEXTVARIABLES : '','','','',''
_COLORVARIABLES : '','','','','',''
_ACCESSLEVELS : 2,2,2,2,2,2,2,2
_OBJECT : 0,0
_THRESH2 : '','','',''
_INPUTTYPE : '','',''
_HIDDENINPUT : 0
_END_ELEM
(* @TEXTSCALINGVARS := '_TEXTSCALINGVARS: $'$',$'$'' *)
(* @EXTENDEDSIMPLESHAPE := '_SIMPLE: 0' *)
(* @INPUTTAPFALSE := '_INPUTTAPFALSE: 0' *)

_SIMPLE : 2
_LINEWIDTH : 0
_NOCOLORS : 1,1
_POS : 325,140,376,166,350,153
_COLORS : 8454016,0,8421631,0,0
_VARIABLES : '','','','','','','',''
_THRESH : '','SF003.Alarm.Adver','',''
_DSP : '','SF003',''
_ZOOM : ''
_INPUT : 0
_TEXT : 5,4294967284,400,0,70,0,0,0
_FONT : ''
_EXEC : ''
_TEXTVARIABLES : '','','','',''
_COLORVARIABLES : '','','','','',''
_ACCESSLEVELS : 2,2,2,2,2,2,2,2
_OBJECT : 0,0
_THRESH2 : '','','',''
_INPUTTYPE : '','',''
_HIDDENINPUT : 0
_END_ELEM
(* @TEXTSCALINGVARS := '_TEXTSCALINGVARS: $'$',$'$'' *)
(* @EXTENDEDSIMPLESHAPE := '_SIMPLE: 0' *)
(* @INPUTTAPFALSE := '_INPUTTAPFALSE: 0' *)

_SIMPLE : 2
_LINEWIDTH : 0
_NOCOLORS : 1,1
_POS : 280,205,331,231,305,218
_COLORS : 8454016,0,8421631,0,0
_VARIABLES : '','','','','','','',''
_THRESH : '','SF005.Alarm.Adver','',''
_DSP : '','SF005',''
_ZOOM : ''
_INPUT : 0
_TEXT : 5,4294967284,400,0,72,0,0,0
_FONT : ''
_EXEC : ''
_TEXTVARIABLES : '','','','',''
_COLORVARIABLES : '','','','','',''
_ACCESSLEVELS : 2,2,2,2,2,2,2,2
_OBJECT : 0,0
_THRESH2 : '','','',''
_INPUTTYPE : '','',''
_HIDDENINPUT : 0
_END_ELEM
(* @TEXTSCALINGVARS := '_TEXTSCALINGVARS: $'$',$'$'' *)
(* @EXTENDEDSIMPLESHAPE := '_SIMPLE: 0' *)
(* @INPUTTAPFALSE := '_INPUTTAPFALSE: 0' *)

_SIMPLE : 2
_LINEWIDTH : 0
_NOCOLORS : 1,1
_POS : 305,430,356,456,330,443
_COLORS : 8454016,0,8421631,0,0
_VARIABLES : '','','','','','','',''
_THRESH : '','SF007.Alarm.Adver','',''
_DSP : '','SF007',''
_ZOOM : ''
_INPUT : 0
_TEXT : 5,4294967284,400,0,74,0,0,0
_FONT : ''
_EXEC : ''
_TEXTVARIABLES : '','','','',''
_COLORVARIABLES : '','','','','',''
_ACCESSLEVELS : 2,2,2,2,2,2,2,2
_OBJECT : 0,0
_THRESH2 : '','','',''
_INPUTTYPE : '','',''
_HIDDENINPUT : 0
_END_ELEM
(* @TEXTSCALINGVARS := '_TEXTSCALINGVARS: $'$',$'$'' *)
(* @EXTENDEDSIMPLESHAPE := '_SIMPLE: 0' *)
(* @INPUTTAPFALSE := '_INPUTTAPFALSE: 0' *)

_SIMPLE : 2
_LINEWIDTH : 0
_NOCOLORS : 1,1
_POS : 525,100,576,126,550,113
_COLORS : 8454016,0,8421631,0,0
_VARIABLES : '','','','','','','',''
_THRESH : '','SF001.Alarm.Adver','',''
_DSP : '','SF001',''
_ZOOM : ''
_INPUT : 0
_TEXT : 5,4294967284,400,0,76,0,0,0
_FONT : ''
_EXEC : ''
_TEXTVARIABLES : '','','','',''
_COLORVARIABLES : '','','','','',''
_ACCESSLEVELS : 2,2,2,2,2,2,2,2
_OBJECT : 0,0
_THRESH2 : '','','',''
_INPUTTYPE : '','',''
_HIDDENINPUT : 0
_END_ELEM
(* @TEXTSCALINGVARS := '_TEXTSCALINGVARS: $'$',$'$'' *)
(* @EXTENDEDSIMPLESHAPE := '_SIMPLE: 0' *)
(* @INPUTTAPFALSE := '_INPUTTAPFALSE: 0' *)

_SIMPLE : 0
_LINEWIDTH : 0
_NOCOLORS : 1,1
_POS : 410,475,506,501,458,488
_COLORS : 12632256,0,8421631,0,0
_VARIABLES : '','','','','','','',''
_THRESH : '','S011.Alarm.Adver','',''
_DSP : 'S011.Deg','S011: %.0f °C',''
_ZOOM : ''
_INPUT : 0
_TEXT : 5,4294967285,700,0,78,0,0,0
_FONT : 'MS Sans Serif'
_EXEC : ''
_TEXTVARIABLES : '','','','',''
_COLORVARIABLES : '','','','','',''
_ACCESSLEVELS : 2,2,2,2,2,2,2,2
_OBJECT : 0,0
_THRESH2 : '','','',''
_INPUTTYPE : '','',''
_HIDDENINPUT : 0
_END_ELEM
(* @TEXTSCALINGVARS := '_TEXTSCALINGVARS: $'$',$'$'' *)
(* @EXTENDEDSIMPLESHAPE := '_SIMPLE: 0' *)
(* @INPUTTAPFALSE := '_INPUTTAPFALSE: 0' *)

_SIMPLE : 1
_LINEWIDTH : 0
_NOCOLORS : 1,1
_POS : 510,475,561,501,535,488
_COLORS : 8454143,0,33023,0,0
_VARIABLES : '','','','','','','',''
_THRESH : '','TANK.S011_Mute','TANK.S011_Mute',''
_DSP : '','MUTE',''
_ZOOM : ''
_INPUT : 65536
_TEXT : 5,4294967284,400,0,79,0,0,0
_FONT : ''
_EXEC : ''
_TEXTVARIABLES : '','','','',''
_COLORVARIABLES : '','','','','',''
_ACCESSLEVELS : 2,2,2,2,2,2,2,2
_OBJECT : 0,0
_THRESH2 : '','','',''
_INPUTTYPE : '','',''
_HIDDENINPUT : 0
_END_ELEM
(* @TEXTSCALINGVARS := '_TEXTSCALINGVARS: $'$',$'$'' *)
(* @EXTENDEDSIMPLESHAPE := '_SIMPLE: 0' *)
(* @INPUTTAPFALSE := '_INPUTTAPFALSE: 0' *)

_SIMPLE : 2
_LINEWIDTH : 0
_NOCOLORS : 1,1
_POS : 495,245,546,271,520,258
_COLORS : 8454016,0,8421631,0,0
_VARIABLES : '','','','','','','',''
_THRESH : '','SF009.Alarm.Adver','',''
_DSP : '','SF009',''
_ZOOM : ''
_INPUT : 0
_TEXT : 5,4294967284,400,0,85,0,0,0
_FONT : ''
_EXEC : ''
_TEXTVARIABLES : '','','','',''
_COLORVARIABLES : '','','','','',''
_ACCESSLEVELS : 2,2,2,2,2,2,2,2
_OBJECT : 0,0
_THRESH2 : '','','',''
_INPUTTYPE : '','',''
_HIDDENINPUT : 0
_END_ELEM
(* @TEXTSCALINGVARS := '_TEXTSCALINGVARS: $'$',$'$'' *)
(* @EXTENDEDSIMPLESHAPE := '_SIMPLE: 0' *)
(* @INPUTTAPFALSE := '_INPUTTAPFALSE: 0' *)

_SIMPLE : 2
_LINEWIDTH : 0
_NOCOLORS : 1,1
_POS : 915,170,1006,211,960,190
_COLORS : 8421631,0,8454016,0,0
_VARIABLES : '','','','','','','',''
_THRESH : 'TANK.Reduced = FALSE','','',''
_DSP : '','REDUCED',''
_ZOOM : ''
_INPUT : 0
_TEXT : 5,4294967283,700,0,86,0,0,0
_FONT : 'MS Sans Serif'
_EXEC : ''
_TEXTVARIABLES : '','','','',''
_COLORVARIABLES : '','','','','',''
_ACCESSLEVELS : 2,2,2,2,2,2,2,2
_OBJECT : 0,0
_THRESH2 : '','','',''
_INPUTTYPE : '','',''
_HIDDENINPUT : 0
_END_ELEM
(* @TEXTSCALINGVARS := '_TEXTSCALINGVARS: $'$',$'$'' *)
(* @EXTENDEDSIMPLESHAPE := '_SIMPLE: 0' *)
(* @INPUTTAPFALSE := '_INPUTTAPFALSE: 0' *)

_SIMPLE : 1
_LINEWIDTH : 0
_NOCOLORS : 1,1
_POS : 550,245,601,271,575,258
_COLORS : 8454143,0,33023,0,0
_VARIABLES : '','','','','','','',''
_THRESH : '','TANK.BypassLevel','TANK.BypassLevel',''
_DSP : '','BYPASS',''
_ZOOM : ''
_INPUT : 65536
_TEXT : 5,4294967284,400,0,91,0,0,0
_FONT : ''
_EXEC : ''
_TEXTVARIABLES : '','','','',''
_COLORVARIABLES : '','','','','',''
_ACCESSLEVELS : 2,2,2,2,2,2,2,2
_OBJECT : 0,0
_THRESH2 : '','','',''
_INPUTTYPE : '','',''
_HIDDENINPUT : 0
_END_ELEM
(* @TEXTSCALINGVARS := '_TEXTSCALINGVARS: $'$',$'$'' *)
(* @EXTENDEDSIMPLESHAPE := '_SIMPLE: 0' *)
(* @INPUTTAPFALSE := '_INPUTTAPFALSE: 0' *)

_SIMPLE : 1
_LINEWIDTH : 0
_NOCOLORS : 1,1
_POS : 900,105,1021,156,960,130
_COLORS : 16777215,0,16777215,0,0
_VARIABLES : '','','','','','','',''
_THRESH : '','','',''
_DSP : '','',''
_ZOOM : ''
_INPUT : 0
_TEXT : 5,4294967284,400,0,93,0,0,0
_FONT : ''
_EXEC : ''
_TEXTVARIABLES : '','','','',''
_COLORVARIABLES : '','','','','',''
_ACCESSLEVELS : 2,2,2,2,2,2,2,2
_OBJECT : 0,0
_THRESH2 : '','','',''
_INPUTTYPE : '','',''
_HIDDENINPUT : 0
_END_ELEM
(* @TEXTSCALINGVARS := '_TEXTSCALINGVARS: $'$',$'$'' *)
(* @EXTENDEDSIMPLESHAPE := '_SIMPLE: 0' *)
(* @INPUTTAPFALSE := '_INPUTTAPFALSE: 0' *)

_SIMPLE : 1
_LINEWIDTH : 0
_NOCOLORS : 1,1
_POS : 905,110,1016,151,960,130
_COLORS : 16776960,0,16744448,0,0
_VARIABLES : '','','','','','','',''
_THRESH : '','ALARMS.Clear','','ALARMS.Clear'
_DSP : '','CLEAR',''
_ZOOM : ''
_INPUT : 131072
_TEXT : 5,4294967283,700,0,94,0,0,0
_FONT : 'MS Sans Serif'
_EXEC : ''
_TEXTVARIABLES : '','','','',''
_COLORVARIABLES : '','','','','',''
_ACCESSLEVELS : 2,2,2,2,2,2,2,2
_OBJECT : 0,0
_THRESH2 : '','','',''
_INPUTTYPE : '','',''
_HIDDENINPUT : 0
_END_ELEM
(* @TEXTSCALINGVARS := '_TEXTSCALINGVARS: $'$',$'$'' *)
(* @EXTENDEDSIMPLESHAPE := '_SIMPLE: 0' *)
(* @INPUTTAPFALSE := '_INPUTTAPFALSE: 0' *)
_KEYINFOLIST : 0
END_VISUALISATION
