(* @PATH := '' *)

VISUALISATION VISU_CFG_WB _VISU_TYPES : 1,1
_BG_BMP : 'visu_background.bmp'
_TEXT : 901
_PAINTZOOM : 100

_SIMPLE : 0
_LINEWIDTH : 0
_NOCOLORS : 1,1
_POS : 20,70,131,531,75,300
_COLORS : 12828343,0,16777215,0,0
_VARIABLES : '','','','','','','',''
_THRESH : '','','',''
_DSP : '','',''
_ZOOM : ''
_INPUT : 0
_TEXT : 5,4294967284,400,0,878,0,0,0
_FONT : ''
_EXEC : ''
_TEXTVARIABLES : '','','','',''
_COLORVARIABLES : '','','','','',''
_ACCESSLEVELS : 2,2,2,2,2,2,2,2
_OBJECT : 0,0
_THRESH2 : '','','',''
_INPUTTYPE : '','',''
_HIDDENINPUT : 0
_END_ELEM
(* @TEXTSCALINGVARS := '_TEXTSCALINGVARS: $'$',$'$'' *)
(* @EXTENDEDSIMPLESHAPE := '_SIMPLE: 0' *)
(* @INPUTTAPFALSE := '_INPUTTAPFALSE: 0' *)

_SIMPLE : 0
_LINEWIDTH : 0
_NOCOLORS : 1,1
_POS : 260,70,371,531,315,300
_COLORS : 12828343,0,16777215,0,0
_VARIABLES : '','','','','','','',''
_THRESH : '','','',''
_DSP : '','',''
_ZOOM : ''
_INPUT : 0
_TEXT : 5,4294967284,400,0,799,0,0,0
_FONT : ''
_EXEC : ''
_TEXTVARIABLES : '','','','',''
_COLORVARIABLES : '','','','','',''
_ACCESSLEVELS : 2,2,2,2,2,2,2,2
_OBJECT : 0,0
_THRESH2 : '','','',''
_INPUTTYPE : '','',''
_HIDDENINPUT : 0
_END_ELEM
(* @TEXTSCALINGVARS := '_TEXTSCALINGVARS: $'$',$'$'' *)
(* @EXTENDEDSIMPLESHAPE := '_SIMPLE: 0' *)
(* @INPUTTAPFALSE := '_INPUTTAPFALSE: 0' *)

_SIMPLE : 0
_LINEWIDTH : 0
_NOCOLORS : 0,0
_POS : 20,550,331,601,175,575
_COLORS : 16777215,0,16777215,0,16777215
_VARIABLES : '','','','','','','',''
_THRESH : '','','',''
_DSP : 'INPUTS.sVisuTime','%s',''
_ZOOM : ''
_INPUT : 0
_TEXT : 4,4294967264,700,0,153,0,0,0
_FONT : 'MS Sans Serif'
_EXEC : ''
_TEXTVARIABLES : '','','','',''
_COLORVARIABLES : '','','','','',''
_ACCESSLEVELS : 2,2,2,2,2,2,2,2
_OBJECT : 0,0
_THRESH2 : '','','',''
_INPUTTYPE : '','',''
_HIDDENINPUT : 0
_END_ELEM
(* @TEXTSCALINGVARS := '_TEXTSCALINGVARS: $'$',$'$'' *)
(* @EXTENDEDSIMPLESHAPE := '_SIMPLE: 0' *)
(* @INPUTTAPFALSE := '_INPUTTAPFALSE: 0' *)

_SIMPLE : 1
_LINEWIDTH : 0
_NOCOLORS : 1,1
_POS : 900,50,1021,101,960,75
_COLORS : 16777215,0,16777215,0,0
_VARIABLES : '','','','','','','',''
_THRESH : '','','',''
_DSP : '','',''
_ZOOM : ''
_INPUT : 0
_TEXT : 5,4294967284,400,0,312,0,0,0
_FONT : ''
_EXEC : ''
_TEXTVARIABLES : '','','','',''
_COLORVARIABLES : '','','','','',''
_ACCESSLEVELS : 2,2,2,2,2,2,2,2
_OBJECT : 0,0
_THRESH2 : '','','',''
_INPUTTYPE : '','',''
_HIDDENINPUT : 0
_END_ELEM
(* @TEXTSCALINGVARS := '_TEXTSCALINGVARS: $'$',$'$'' *)
(* @EXTENDEDSIMPLESHAPE := '_SIMPLE: 0' *)
(* @INPUTTAPFALSE := '_INPUTTAPFALSE: 0' *)

_SIMPLE : 1
_LINEWIDTH : 0
_NOCOLORS : 1,1
_POS : 905,55,1016,96,960,75
_COLORS : 12615680,0,8404992,0,16777215
_VARIABLES : '','','','','','','',''
_THRESH : '','PARAMS.Save','PARAMS.Save',''
_DSP : '','SAVE',''
_ZOOM : ''
_INPUT : 65536
_TEXT : 5,4294967283,700,0,313,0,0,0
_FONT : 'MS Sans Serif'
_EXEC : ''
_TEXTVARIABLES : '','','','',''
_COLORVARIABLES : '','','','','',''
_ACCESSLEVELS : 2,2,2,2,2,2,2,2
_OBJECT : 0,0
_THRESH2 : '','','',''
_INPUTTYPE : '','',''
_HIDDENINPUT : 0
_END_ELEM
(* @TEXTSCALINGVARS := '_TEXTSCALINGVARS: $'$',$'$'' *)
(* @EXTENDEDSIMPLESHAPE := '_SIMPLE: 0' *)
(* @INPUTTAPFALSE := '_INPUTTAPFALSE: 0' *)

_SIMPLE : 1
_LINEWIDTH : 0
_NOCOLORS : 1,1
_POS : 900,500,1021,551,960,525
_COLORS : 16777215,0,16777215,0,0
_VARIABLES : '','','','','','','',''
_THRESH : '','','',''
_DSP : '','',''
_ZOOM : ''
_INPUT : 0
_TEXT : 5,4294967284,400,0,314,0,0,0
_FONT : ''
_EXEC : ''
_TEXTVARIABLES : '','','','',''
_COLORVARIABLES : '','','','','',''
_ACCESSLEVELS : 2,2,2,2,2,2,2,2
_OBJECT : 0,0
_THRESH2 : '','','',''
_INPUTTYPE : '','',''
_HIDDENINPUT : 0
_END_ELEM
(* @TEXTSCALINGVARS := '_TEXTSCALINGVARS: $'$',$'$'' *)
(* @EXTENDEDSIMPLESHAPE := '_SIMPLE: 0' *)
(* @INPUTTAPFALSE := '_INPUTTAPFALSE: 0' *)

_SIMPLE : 1
_LINEWIDTH : 0
_NOCOLORS : 1,1
_POS : 905,505,1016,546,960,525
_COLORS : 2105379,2105379,16777215,0,16777215
_VARIABLES : '','','','','','','',''
_THRESH : '','','',''
_DSP : '','RETURN',''
_ZOOM : 'VISU_1_WB'
_INPUT : 262144
_TEXT : 5,4294967283,700,0,315,0,0,0
_FONT : 'MS Sans Serif'
_EXEC : ''
_TEXTVARIABLES : '','','','',''
_COLORVARIABLES : '','','','','',''
_ACCESSLEVELS : 2,2,2,2,2,2,2,2
_OBJECT : 0,0
_THRESH2 : '','','',''
_INPUTTYPE : '','',''
_HIDDENINPUT : 0
_END_ELEM
(* @TEXTSCALINGVARS := '_TEXTSCALINGVARS: $'$',$'$'' *)
(* @EXTENDEDSIMPLESHAPE := '_SIMPLE: 0' *)
(* @INPUTTAPFALSE := '_INPUTTAPFALSE: 0' *)

_SIMPLE : 0
_LINEWIDTH : 0
_NOCOLORS : 0,0
_POS : 730,550,896,601,813,575
_COLORS : 16777215,0,16777215,0,16777215
_VARIABLES : '','','','','','','',''
_THRESH : 'PARAMS.Saved','','',''
_DSP : '','SAVED!',''
_ZOOM : ''
_INPUT : 0
_TEXT : 5,4294967264,700,0,651,0,0,0
_FONT : 'MS Sans Serif'
_EXEC : ''
_TEXTVARIABLES : '','','','',''
_COLORVARIABLES : '','','','','',''
_ACCESSLEVELS : 2,2,2,2,2,2,2,2
_OBJECT : 0,0
_THRESH2 : '','','',''
_INPUTTYPE : '','',''
_HIDDENINPUT : 0
_END_ELEM
(* @TEXTSCALINGVARS := '_TEXTSCALINGVARS: $'$',$'$'' *)
(* @EXTENDEDSIMPLESHAPE := '_SIMPLE: 0' *)
(* @INPUTTAPFALSE := '_INPUTTAPFALSE: 0' *)

_SIMPLE : 0
_LINEWIDTH : 0
_NOCOLORS : 1,1
_POS : 140,70,251,531,195,300
_COLORS : 12828343,0,16777215,0,0
_VARIABLES : '','','','','','','',''
_THRESH : '','','',''
_DSP : '','',''
_ZOOM : ''
_INPUT : 0
_TEXT : 5,4294967284,400,0,652,0,0,0
_FONT : ''
_EXEC : ''
_TEXTVARIABLES : '','','','',''
_COLORVARIABLES : '','','','','',''
_ACCESSLEVELS : 2,2,2,2,2,2,2,2
_OBJECT : 0,0
_THRESH2 : '','','',''
_INPUTTYPE : '','',''
_HIDDENINPUT : 0
_END_ELEM
(* @TEXTSCALINGVARS := '_TEXTSCALINGVARS: $'$',$'$'' *)
(* @EXTENDEDSIMPLESHAPE := '_SIMPLE: 0' *)
(* @INPUTTAPFALSE := '_INPUTTAPFALSE: 0' *)

_SIMPLE : 0
_LINEWIDTH : 0
_NOCOLORS : 0,0
_POS : 160,90,231,106,195,98
_COLORS : 16777215,0,16776960,16777215,0
_VARIABLES : '','','','','','','',''
_THRESH : '','','',''
_DSP : '','Time Max',''
_ZOOM : ''
_INPUT : 0
_TEXT : 5,4294967285,400,0,655,0,0,0
_FONT : 'MS Sans Serif'
_EXEC : ''
_TEXTVARIABLES : '','','','',''
_COLORVARIABLES : '','','','','',''
_ACCESSLEVELS : 2,2,2,2,2,2,2,2
_OBJECT : 0,0
_THRESH2 : '','','',''
_INPUTTYPE : '','',''
_HIDDENINPUT : 0
_END_ELEM
(* @TEXTSCALINGVARS := '_TEXTSCALINGVARS: $'$',$'$'' *)
(* @EXTENDEDSIMPLESHAPE := '_SIMPLE: 0' *)
(* @INPUTTAPFALSE := '_INPUTTAPFALSE: 0' *)

_SIMPLE : 0
_LINEWIDTH : 0
_NOCOLORS : 0,0
_POS : 160,190,231,206,195,198
_COLORS : 16777215,0,16776960,16777215,0
_VARIABLES : '','','','','','','',''
_THRESH : '','','',''
_DSP : '','Push Press.',''
_ZOOM : ''
_INPUT : 0
_TEXT : 5,4294967285,400,0,686,0,0,0
_FONT : 'MS Sans Serif'
_EXEC : ''
_TEXTVARIABLES : '','','','',''
_COLORVARIABLES : '','','','','',''
_ACCESSLEVELS : 2,2,2,2,2,2,2,2
_OBJECT : 0,0
_THRESH2 : '','','',''
_INPUTTYPE : '','',''
_HIDDENINPUT : 0
_END_ELEM
(* @TEXTSCALINGVARS := '_TEXTSCALINGVARS: $'$',$'$'' *)
(* @EXTENDEDSIMPLESHAPE := '_SIMPLE: 0' *)
(* @INPUTTAPFALSE := '_INPUTTAPFALSE: 0' *)

_SIMPLE : 0
_LINEWIDTH : 0
_NOCOLORS : 0,1
_POS : 170,55,221,86,195,70
_COLORS : 12828343,8388608,16776960,16777215,0
_VARIABLES : '','','','','','','',''
_THRESH : '','','',''
_DSP : '','SMALL$R$NVALVES',''
_ZOOM : ''
_INPUT : 0
_TEXT : 5,4294967285,400,0,703,0,0,0
_FONT : 'MS Sans Serif'
_EXEC : ''
_TEXTVARIABLES : '','','','',''
_COLORVARIABLES : '','','','','',''
_ACCESSLEVELS : 2,2,2,2,2,2,2,2
_OBJECT : 0,0
_THRESH2 : '','','',''
_INPUTTYPE : '','',''
_HIDDENINPUT : 0
_END_ELEM
(* @TEXTSCALINGVARS := '_TEXTSCALINGVARS: $'$',$'$'' *)
(* @EXTENDEDSIMPLESHAPE := '_SIMPLE: 0' *)
(* @INPUTTAPFALSE := '_INPUTTAPFALSE: 0' *)

_SIMPLE : 0
_LINEWIDTH : 0
_NOCOLORS : 0,1
_POS : 290,55,341,86,315,70
_COLORS : 12828343,8388608,16776960,16777215,0
_VARIABLES : '','','','','','','',''
_THRESH : '','','',''
_DSP : '','BIG$R$NVALVES',''
_ZOOM : ''
_INPUT : 0
_TEXT : 5,4294967285,400,0,704,0,0,0
_FONT : 'MS Sans Serif'
_EXEC : ''
_TEXTVARIABLES : '','','','',''
_COLORVARIABLES : '','','','','',''
_ACCESSLEVELS : 2,2,2,2,2,2,2,2
_OBJECT : 0,0
_THRESH2 : '','','',''
_INPUTTYPE : '','',''
_HIDDENINPUT : 0
_END_ELEM
(* @TEXTSCALINGVARS := '_TEXTSCALINGVARS: $'$',$'$'' *)
(* @EXTENDEDSIMPLESHAPE := '_SIMPLE: 0' *)
(* @INPUTTAPFALSE := '_INPUTTAPFALSE: 0' *)

_SIMPLE : 0
_LINEWIDTH : 0
_NOCOLORS : 1,1
_POS : 160,165,231,186,195,175
_COLORS : 16777215,0,16777215,0,0
_VARIABLES : '','','','','','','',''
_THRESH : '','','',''
_DSP : 'PARAMS.stWBValveSFCfg.PushTime','%.1f s ',''
_ZOOM : ''
_INPUT : 1048576
_TEXT : 6,4294967283,400,0,709,0,0,0
_FONT : 'MS Sans Serif'
_EXEC : 'INTERN ASSIGN INPUTS.PresSelCalStbd[9]:=(FALSE)'
_TEXTVARIABLES : '','','','',''
_COLORVARIABLES : '','','','','',''
_ACCESSLEVELS : 2,2,2,2,2,2,2,2
_OBJECT : 0,1
_THRESH2 : '','','',''
_INPUTTYPE : '','',''
_HIDDENINPUT : 0
_END_ELEM
(* @TEXTSCALINGVARS := '_TEXTSCALINGVARS: $'$',$'$'' *)
(* @EXTENDEDSIMPLESHAPE := '_SIMPLE: 0' *)
(* @INPUTTAPFALSE := '_INPUTTAPFALSE: 0' *)

_SIMPLE : 0
_LINEWIDTH : 0
_NOCOLORS : 0,0
_POS : 160,150,231,166,195,158
_COLORS : 16777215,0,16776960,16777215,0
_VARIABLES : '','','','','','','',''
_THRESH : '','','',''
_DSP : '','Push Time',''
_ZOOM : ''
_INPUT : 0
_TEXT : 5,4294967285,400,0,710,0,0,0
_FONT : 'MS Sans Serif'
_EXEC : ''
_TEXTVARIABLES : '','','','',''
_COLORVARIABLES : '','','','','',''
_ACCESSLEVELS : 2,2,2,2,2,2,2,2
_OBJECT : 0,0
_THRESH2 : '','','',''
_INPUTTYPE : '','',''
_HIDDENINPUT : 0
_END_ELEM
(* @TEXTSCALINGVARS := '_TEXTSCALINGVARS: $'$',$'$'' *)
(* @EXTENDEDSIMPLESHAPE := '_SIMPLE: 0' *)
(* @INPUTTAPFALSE := '_INPUTTAPFALSE: 0' *)

_SIMPLE : 0
_LINEWIDTH : 0
_NOCOLORS : 1,1
_POS : 160,365,231,386,195,375
_COLORS : 16777215,0,16777215,0,0
_VARIABLES : '','','','','','','',''
_THRESH : '','','',''
_DSP : 'PARAMS.stWBValveSFCfg.HP','%d ',''
_ZOOM : ''
_INPUT : 1048576
_TEXT : 6,4294967283,400,0,711,0,0,0
_FONT : 'MS Sans Serif'
_EXEC : 'INTERN ASSIGN INPUTS.PresSelCalStbd[9]:=(FALSE)'
_TEXTVARIABLES : '','','','',''
_COLORVARIABLES : '','','','','',''
_ACCESSLEVELS : 2,2,2,2,2,2,2,2
_OBJECT : 0,1
_THRESH2 : '','','',''
_INPUTTYPE : '1','2',''
_HIDDENINPUT : 0
_END_ELEM
(* @TEXTSCALINGVARS := '_TEXTSCALINGVARS: $'$',$'$'' *)
(* @EXTENDEDSIMPLESHAPE := '_SIMPLE: 0' *)
(* @INPUTTAPFALSE := '_INPUTTAPFALSE: 0' *)

_SIMPLE : 0
_LINEWIDTH : 0
_NOCOLORS : 0,0
_POS : 160,350,231,366,195,358
_COLORS : 16777215,0,16776960,16777215,0
_VARIABLES : '','','','','','','',''
_THRESH : '','','',''
_DSP : '','HP Pumps',''
_ZOOM : ''
_INPUT : 0
_TEXT : 5,4294967285,400,0,712,0,0,0
_FONT : 'MS Sans Serif'
_EXEC : ''
_TEXTVARIABLES : '','','','',''
_COLORVARIABLES : '','','','','',''
_ACCESSLEVELS : 2,2,2,2,2,2,2,2
_OBJECT : 0,0
_THRESH2 : '','','',''
_INPUTTYPE : '','',''
_HIDDENINPUT : 0
_END_ELEM
(* @TEXTSCALINGVARS := '_TEXTSCALINGVARS: $'$',$'$'' *)
(* @EXTENDEDSIMPLESHAPE := '_SIMPLE: 0' *)
(* @INPUTTAPFALSE := '_INPUTTAPFALSE: 0' *)

_SIMPLE : 0
_LINEWIDTH : 0
_NOCOLORS : 1,1
_POS : 280,265,351,286,315,275
_COLORS : 16777215,0,16777215,0,0
_VARIABLES : '','','','','','','',''
_THRESH : '','','',''
_DSP : 'PARAMS.stWBValveLSCfg.TgtLS_Half','%.1f %% ',''
_ZOOM : ''
_INPUT : 1048576
_TEXT : 6,4294967283,400,0,720,0,0,0
_FONT : 'MS Sans Serif'
_EXEC : 'INTERN ASSIGN INPUTS.PresSelCalStbd[9]:=(FALSE)'
_TEXTVARIABLES : '','','','',''
_COLORVARIABLES : '','','','','',''
_ACCESSLEVELS : 2,2,2,2,2,2,2,2
_OBJECT : 0,1
_THRESH2 : '','','',''
_INPUTTYPE : '','',''
_HIDDENINPUT : 0
_END_ELEM
(* @TEXTSCALINGVARS := '_TEXTSCALINGVARS: $'$',$'$'' *)
(* @EXTENDEDSIMPLESHAPE := '_SIMPLE: 0' *)
(* @INPUTTAPFALSE := '_INPUTTAPFALSE: 0' *)

_SIMPLE : 0
_LINEWIDTH : 0
_NOCOLORS : 0,0
_POS : 280,90,351,106,315,98
_COLORS : 16777215,0,16776960,16777215,0
_VARIABLES : '','','','','','','',''
_THRESH : '','','',''
_DSP : '','Time Max',''
_ZOOM : ''
_INPUT : 0
_TEXT : 5,4294967285,400,0,721,0,0,0
_FONT : 'MS Sans Serif'
_EXEC : ''
_TEXTVARIABLES : '','','','',''
_COLORVARIABLES : '','','','','',''
_ACCESSLEVELS : 2,2,2,2,2,2,2,2
_OBJECT : 0,0
_THRESH2 : '','','',''
_INPUTTYPE : '','',''
_HIDDENINPUT : 0
_END_ELEM
(* @TEXTSCALINGVARS := '_TEXTSCALINGVARS: $'$',$'$'' *)
(* @EXTENDEDSIMPLESHAPE := '_SIMPLE: 0' *)
(* @INPUTTAPFALSE := '_INPUTTAPFALSE: 0' *)

_SIMPLE : 0
_LINEWIDTH : 0
_NOCOLORS : 0,0
_POS : 280,250,351,266,315,258
_COLORS : 16777215,0,16776960,16777215,0
_VARIABLES : '','','','','','','',''
_THRESH : '','','',''
_DSP : '','Pos. 1/2',''
_ZOOM : ''
_INPUT : 0
_TEXT : 5,4294967285,400,0,722,0,0,0
_FONT : 'MS Sans Serif'
_EXEC : ''
_TEXTVARIABLES : '','','','',''
_COLORVARIABLES : '','','','','',''
_ACCESSLEVELS : 2,2,2,2,2,2,2,2
_OBJECT : 0,0
_THRESH2 : '','','',''
_INPUTTYPE : '','',''
_HIDDENINPUT : 0
_END_ELEM
(* @TEXTSCALINGVARS := '_TEXTSCALINGVARS: $'$',$'$'' *)
(* @EXTENDEDSIMPLESHAPE := '_SIMPLE: 0' *)
(* @INPUTTAPFALSE := '_INPUTTAPFALSE: 0' *)

_SIMPLE : 0
_LINEWIDTH : 0
_NOCOLORS : 1,1
_POS : 280,305,351,326,315,315
_COLORS : 16777215,0,16777215,0,0
_VARIABLES : '','','','','','','',''
_THRESH : '','','',''
_DSP : 'PARAMS.stWBValveLSCfg.LS_DB','%.1f %% ',''
_ZOOM : ''
_INPUT : 1048576
_TEXT : 6,4294967283,400,0,727,0,0,0
_FONT : 'MS Sans Serif'
_EXEC : 'INTERN ASSIGN INPUTS.PresSelCalStbd[9]:=(FALSE)'
_TEXTVARIABLES : '','','','',''
_COLORVARIABLES : '','','','','',''
_ACCESSLEVELS : 2,2,2,2,2,2,2,2
_OBJECT : 0,1
_THRESH2 : '','','',''
_INPUTTYPE : '','',''
_HIDDENINPUT : 0
_END_ELEM
(* @TEXTSCALINGVARS := '_TEXTSCALINGVARS: $'$',$'$'' *)
(* @EXTENDEDSIMPLESHAPE := '_SIMPLE: 0' *)
(* @INPUTTAPFALSE := '_INPUTTAPFALSE: 0' *)

_SIMPLE : 0
_LINEWIDTH : 0
_NOCOLORS : 0,0
_POS : 280,290,351,306,315,298
_COLORS : 16777215,0,16776960,16777215,0
_VARIABLES : '','','','','','','',''
_THRESH : '','','',''
_DSP : '','Pos. DB',''
_ZOOM : ''
_INPUT : 0
_TEXT : 5,4294967285,400,0,728,0,0,0
_FONT : 'MS Sans Serif'
_EXEC : ''
_TEXTVARIABLES : '','','','',''
_COLORVARIABLES : '','','','','',''
_ACCESSLEVELS : 2,2,2,2,2,2,2,2
_OBJECT : 0,0
_THRESH2 : '','','',''
_INPUTTYPE : '','',''
_HIDDENINPUT : 0
_END_ELEM
(* @TEXTSCALINGVARS := '_TEXTSCALINGVARS: $'$',$'$'' *)
(* @EXTENDEDSIMPLESHAPE := '_SIMPLE: 0' *)
(* @INPUTTAPFALSE := '_INPUTTAPFALSE: 0' *)

_SIMPLE : 0
_LINEWIDTH : 0
_NOCOLORS : 0,0
_POS : 20,0,426,51,223,25
_COLORS : 16777215,0,16777215,0,16777215
_VARIABLES : '','','','','','','',''
_THRESH : '','','',''
_DSP : '','CFG: WATER BALLAST',''
_ZOOM : ''
_INPUT : 0
_TEXT : 4,4294967264,700,0,778,0,0,0
_FONT : 'MS Sans Serif'
_EXEC : ''
_TEXTVARIABLES : '','','','',''
_COLORVARIABLES : '','','','','',''
_ACCESSLEVELS : 2,2,2,2,2,2,2,2
_OBJECT : 0,0
_THRESH2 : '','','',''
_INPUTTYPE : '','',''
_HIDDENINPUT : 0
_END_ELEM
(* @TEXTSCALINGVARS := '_TEXTSCALINGVARS: $'$',$'$'' *)
(* @EXTENDEDSIMPLESHAPE := '_SIMPLE: 0' *)
(* @INPUTTAPFALSE := '_INPUTTAPFALSE: 0' *)

_SIMPLE : 0
_LINEWIDTH : 0
_NOCOLORS : 1,1
_POS : 160,105,231,126,195,115
_COLORS : 16777215,0,16777215,0,0
_VARIABLES : '','','','','','','',''
_THRESH : '','','',''
_DSP : 'PARAMS.stWBValveSFCfg.TimeMax','%.0f s ',''
_ZOOM : ''
_INPUT : 1048576
_TEXT : 6,4294967283,400,0,653,0,0,0
_FONT : 'MS Sans Serif'
_EXEC : 'INTERN ASSIGN INPUTS.PresSelCalStbd[9]:=(FALSE)'
_TEXTVARIABLES : '','','','',''
_COLORVARIABLES : '','','','','',''
_ACCESSLEVELS : 2,2,2,2,2,2,2,2
_OBJECT : 0,1
_THRESH2 : '','','',''
_INPUTTYPE : '','',''
_HIDDENINPUT : 0
_END_ELEM
(* @TEXTSCALINGVARS := '_TEXTSCALINGVARS: $'$',$'$'' *)
(* @EXTENDEDSIMPLESHAPE := '_SIMPLE: 0' *)
(* @INPUTTAPFALSE := '_INPUTTAPFALSE: 0' *)

_SIMPLE : 0
_LINEWIDTH : 0
_NOCOLORS : 1,1
_POS : 280,105,351,126,315,115
_COLORS : 16777215,0,16777215,0,0
_VARIABLES : '','','','','','','',''
_THRESH : '','','',''
_DSP : 'PARAMS.stWBValveLSCfg.TimeMax','%.0f s ',''
_ZOOM : ''
_INPUT : 1048576
_TEXT : 6,4294967283,400,0,719,0,0,0
_FONT : 'MS Sans Serif'
_EXEC : 'INTERN ASSIGN INPUTS.PresSelCalStbd[9]:=(FALSE)'
_TEXTVARIABLES : '','','','',''
_COLORVARIABLES : '','','','','',''
_ACCESSLEVELS : 2,2,2,2,2,2,2,2
_OBJECT : 0,1
_THRESH2 : '','','',''
_INPUTTYPE : '','',''
_HIDDENINPUT : 0
_END_ELEM
(* @TEXTSCALINGVARS := '_TEXTSCALINGVARS: $'$',$'$'' *)
(* @EXTENDEDSIMPLESHAPE := '_SIMPLE: 0' *)
(* @INPUTTAPFALSE := '_INPUTTAPFALSE: 0' *)

_SIMPLE : 0
_LINEWIDTH : 0
_NOCOLORS : 1,1
_POS : 160,205,231,226,195,215
_COLORS : 16777215,0,16777215,0,0
_VARIABLES : '','','','','','','',''
_THRESH : '','','',''
_DSP : 'PARAMS.stWBValveSFCfg.PushP','%.0f bar ',''
_ZOOM : ''
_INPUT : 1048576
_TEXT : 6,4294967283,400,0,685,0,0,0
_FONT : 'MS Sans Serif'
_EXEC : 'INTERN ASSIGN INPUTS.PresSelCalStbd[9]:=(FALSE)'
_TEXTVARIABLES : '','','','',''
_COLORVARIABLES : '','','','','',''
_ACCESSLEVELS : 2,2,2,2,2,2,2,2
_OBJECT : 0,1
_THRESH2 : '','','',''
_INPUTTYPE : '','',''
_HIDDENINPUT : 0
_END_ELEM
(* @TEXTSCALINGVARS := '_TEXTSCALINGVARS: $'$',$'$'' *)
(* @EXTENDEDSIMPLESHAPE := '_SIMPLE: 0' *)
(* @INPUTTAPFALSE := '_INPUTTAPFALSE: 0' *)

_SIMPLE : 0
_LINEWIDTH : 0
_NOCOLORS : 0,0
_POS : 280,190,351,206,315,198
_COLORS : 16777215,0,16776960,16777215,0
_VARIABLES : '','','','','','','',''
_THRESH : '','','',''
_DSP : '','Push Press.',''
_ZOOM : ''
_INPUT : 0
_TEXT : 5,4294967285,400,0,864,0,0,0
_FONT : 'MS Sans Serif'
_EXEC : ''
_TEXTVARIABLES : '','','','',''
_COLORVARIABLES : '','','','','',''
_ACCESSLEVELS : 2,2,2,2,2,2,2,2
_OBJECT : 0,0
_THRESH2 : '','','',''
_INPUTTYPE : '','',''
_HIDDENINPUT : 0
_END_ELEM
(* @TEXTSCALINGVARS := '_TEXTSCALINGVARS: $'$',$'$'' *)
(* @EXTENDEDSIMPLESHAPE := '_SIMPLE: 0' *)
(* @INPUTTAPFALSE := '_INPUTTAPFALSE: 0' *)

_SIMPLE : 0
_LINEWIDTH : 0
_NOCOLORS : 1,1
_POS : 280,165,351,186,315,175
_COLORS : 16777215,0,16777215,0,0
_VARIABLES : '','','','','','','',''
_THRESH : '','','',''
_DSP : 'PARAMS.stWBValveLSCfg.PushTime','%.1f s ',''
_ZOOM : ''
_INPUT : 1048576
_TEXT : 6,4294967283,400,0,865,0,0,0
_FONT : 'MS Sans Serif'
_EXEC : 'INTERN ASSIGN INPUTS.PresSelCalStbd[9]:=(FALSE)'
_TEXTVARIABLES : '','','','',''
_COLORVARIABLES : '','','','','',''
_ACCESSLEVELS : 2,2,2,2,2,2,2,2
_OBJECT : 0,1
_THRESH2 : '','','',''
_INPUTTYPE : '','',''
_HIDDENINPUT : 0
_END_ELEM
(* @TEXTSCALINGVARS := '_TEXTSCALINGVARS: $'$',$'$'' *)
(* @EXTENDEDSIMPLESHAPE := '_SIMPLE: 0' *)
(* @INPUTTAPFALSE := '_INPUTTAPFALSE: 0' *)

_SIMPLE : 0
_LINEWIDTH : 0
_NOCOLORS : 0,0
_POS : 280,150,351,166,315,158
_COLORS : 16777215,0,16776960,16777215,0
_VARIABLES : '','','','','','','',''
_THRESH : '','','',''
_DSP : '','Push Time',''
_ZOOM : ''
_INPUT : 0
_TEXT : 5,4294967285,400,0,866,0,0,0
_FONT : 'MS Sans Serif'
_EXEC : ''
_TEXTVARIABLES : '','','','',''
_COLORVARIABLES : '','','','','',''
_ACCESSLEVELS : 2,2,2,2,2,2,2,2
_OBJECT : 0,0
_THRESH2 : '','','',''
_INPUTTYPE : '','',''
_HIDDENINPUT : 0
_END_ELEM
(* @TEXTSCALINGVARS := '_TEXTSCALINGVARS: $'$',$'$'' *)
(* @EXTENDEDSIMPLESHAPE := '_SIMPLE: 0' *)
(* @INPUTTAPFALSE := '_INPUTTAPFALSE: 0' *)

_SIMPLE : 0
_LINEWIDTH : 0
_NOCOLORS : 1,1
_POS : 280,205,351,226,315,215
_COLORS : 16777215,0,16777215,0,0
_VARIABLES : '','','','','','','',''
_THRESH : '','','',''
_DSP : 'PARAMS.stWBValveLSCfg.PushP','%.0f bar ',''
_ZOOM : ''
_INPUT : 1048576
_TEXT : 6,4294967283,400,0,867,0,0,0
_FONT : 'MS Sans Serif'
_EXEC : 'INTERN ASSIGN INPUTS.PresSelCalStbd[9]:=(FALSE)'
_TEXTVARIABLES : '','','','',''
_COLORVARIABLES : '','','','','',''
_ACCESSLEVELS : 2,2,2,2,2,2,2,2
_OBJECT : 0,1
_THRESH2 : '','','',''
_INPUTTYPE : '','',''
_HIDDENINPUT : 0
_END_ELEM
(* @TEXTSCALINGVARS := '_TEXTSCALINGVARS: $'$',$'$'' *)
(* @EXTENDEDSIMPLESHAPE := '_SIMPLE: 0' *)
(* @INPUTTAPFALSE := '_INPUTTAPFALSE: 0' *)

_SIMPLE : 0
_LINEWIDTH : 0
_NOCOLORS : 1,1
_POS : 280,365,351,386,315,375
_COLORS : 16777215,0,16777215,0,0
_VARIABLES : '','','','','','','',''
_THRESH : '','','',''
_DSP : 'PARAMS.stWBValveLSCfg.HP','%d ',''
_ZOOM : ''
_INPUT : 1048576
_TEXT : 6,4294967283,400,0,868,0,0,0
_FONT : 'MS Sans Serif'
_EXEC : 'INTERN ASSIGN INPUTS.PresSelCalStbd[9]:=(FALSE)'
_TEXTVARIABLES : '','','','',''
_COLORVARIABLES : '','','','','',''
_ACCESSLEVELS : 2,2,2,2,2,2,2,2
_OBJECT : 0,1
_THRESH2 : '','','',''
_INPUTTYPE : '1','2',''
_HIDDENINPUT : 0
_END_ELEM
(* @TEXTSCALINGVARS := '_TEXTSCALINGVARS: $'$',$'$'' *)
(* @EXTENDEDSIMPLESHAPE := '_SIMPLE: 0' *)
(* @INPUTTAPFALSE := '_INPUTTAPFALSE: 0' *)

_SIMPLE : 0
_LINEWIDTH : 0
_NOCOLORS : 0,0
_POS : 280,350,351,366,315,358
_COLORS : 16777215,0,16776960,16777215,0
_VARIABLES : '','','','','','','',''
_THRESH : '','','',''
_DSP : '','HP Pumps',''
_ZOOM : ''
_INPUT : 0
_TEXT : 5,4294967285,400,0,869,0,0,0
_FONT : 'MS Sans Serif'
_EXEC : ''
_TEXTVARIABLES : '','','','',''
_COLORVARIABLES : '','','','','',''
_ACCESSLEVELS : 2,2,2,2,2,2,2,2
_OBJECT : 0,0
_THRESH2 : '','','',''
_INPUTTYPE : '','',''
_HIDDENINPUT : 0
_END_ELEM
(* @TEXTSCALINGVARS := '_TEXTSCALINGVARS: $'$',$'$'' *)
(* @EXTENDEDSIMPLESHAPE := '_SIMPLE: 0' *)
(* @INPUTTAPFALSE := '_INPUTTAPFALSE: 0' *)

_POLY : 2
_LINEWIDTH : 0
_NOCOLORS : 1,1
_POLYSORT : 1
_POS : 195,140,150,140,240,140
_COLORS : 16777215,0,16777215,0,0
_VARIABLES : '','','',''
_THRESH : '','','',''
_INPUT : 0
_DSP : '','',''
_ZOOM : ''
_TEXT : 5,4294967284,400,0,870,0,0,0
_FONT : ''
_EXEC : ''
_TEXTVARIABLES : '','','','',''
_COLORVARIABLES : '','','','','',''
_ACCESSLEVELS : 2,2,2,2,2,2,2,2
_OBJECT : 0,0
_THRESH2 : '','','',''
_INPUTTYPE : '','',''
_HIDDENINPUT : 0
_END_ELEM
(* @TEXTSCALINGVARS := '_TEXTSCALINGVARS: $'$',$'$'' *)
(* @INPUTTAPFALSE := '_INPUTTAPFALSE: 0' *)

_POLY : 2
_LINEWIDTH : 0
_NOCOLORS : 1,1
_POLYSORT : 1
_POS : 315,140,270,140,360,140
_COLORS : 16777215,0,16777215,0,0
_VARIABLES : '','','',''
_THRESH : '','','',''
_INPUT : 0
_DSP : '','',''
_ZOOM : ''
_TEXT : 5,4294967284,400,0,871,0,0,0
_FONT : ''
_EXEC : ''
_TEXTVARIABLES : '','','','',''
_COLORVARIABLES : '','','','','',''
_ACCESSLEVELS : 2,2,2,2,2,2,2,2
_OBJECT : 0,0
_THRESH2 : '','','',''
_INPUTTYPE : '','',''
_HIDDENINPUT : 0
_END_ELEM
(* @TEXTSCALINGVARS := '_TEXTSCALINGVARS: $'$',$'$'' *)
(* @INPUTTAPFALSE := '_INPUTTAPFALSE: 0' *)

_POLY : 2
_LINEWIDTH : 0
_NOCOLORS : 1,1
_POLYSORT : 1
_POS : 195,240,150,240,240,240
_COLORS : 16777215,0,16777215,0,0
_VARIABLES : '','','',''
_THRESH : '','','',''
_INPUT : 0
_DSP : '','',''
_ZOOM : ''
_TEXT : 5,4294967284,400,0,872,0,0,0
_FONT : ''
_EXEC : ''
_TEXTVARIABLES : '','','','',''
_COLORVARIABLES : '','','','','',''
_ACCESSLEVELS : 2,2,2,2,2,2,2,2
_OBJECT : 0,0
_THRESH2 : '','','',''
_INPUTTYPE : '','',''
_HIDDENINPUT : 0
_END_ELEM
(* @TEXTSCALINGVARS := '_TEXTSCALINGVARS: $'$',$'$'' *)
(* @INPUTTAPFALSE := '_INPUTTAPFALSE: 0' *)

_POLY : 2
_LINEWIDTH : 0
_NOCOLORS : 1,1
_POLYSORT : 1
_POS : 315,240,270,240,360,240
_COLORS : 16777215,0,16777215,0,0
_VARIABLES : '','','',''
_THRESH : '','','',''
_INPUT : 0
_DSP : '','',''
_ZOOM : ''
_TEXT : 5,4294967284,400,0,873,0,0,0
_FONT : ''
_EXEC : ''
_TEXTVARIABLES : '','','','',''
_COLORVARIABLES : '','','','','',''
_ACCESSLEVELS : 2,2,2,2,2,2,2,2
_OBJECT : 0,0
_THRESH2 : '','','',''
_INPUTTYPE : '','',''
_HIDDENINPUT : 0
_END_ELEM
(* @TEXTSCALINGVARS := '_TEXTSCALINGVARS: $'$',$'$'' *)
(* @INPUTTAPFALSE := '_INPUTTAPFALSE: 0' *)

_POLY : 2
_LINEWIDTH : 0
_NOCOLORS : 1,1
_POLYSORT : 1
_POS : 195,340,150,340,240,340
_COLORS : 16777215,0,16777215,0,0
_VARIABLES : '','','',''
_THRESH : '','','',''
_INPUT : 0
_DSP : '','',''
_ZOOM : ''
_TEXT : 5,4294967284,400,0,874,0,0,0
_FONT : ''
_EXEC : ''
_TEXTVARIABLES : '','','','',''
_COLORVARIABLES : '','','','','',''
_ACCESSLEVELS : 2,2,2,2,2,2,2,2
_OBJECT : 0,0
_THRESH2 : '','','',''
_INPUTTYPE : '','',''
_HIDDENINPUT : 0
_END_ELEM
(* @TEXTSCALINGVARS := '_TEXTSCALINGVARS: $'$',$'$'' *)
(* @INPUTTAPFALSE := '_INPUTTAPFALSE: 0' *)

_POLY : 2
_LINEWIDTH : 0
_NOCOLORS : 1,1
_POLYSORT : 1
_POS : 315,340,270,340,360,340
_COLORS : 16777215,0,16777215,0,0
_VARIABLES : '','','',''
_THRESH : '','','',''
_INPUT : 0
_DSP : '','',''
_ZOOM : ''
_TEXT : 5,4294967284,400,0,875,0,0,0
_FONT : ''
_EXEC : ''
_TEXTVARIABLES : '','','','',''
_COLORVARIABLES : '','','','','',''
_ACCESSLEVELS : 2,2,2,2,2,2,2,2
_OBJECT : 0,0
_THRESH2 : '','','',''
_INPUTTYPE : '','',''
_HIDDENINPUT : 0
_END_ELEM
(* @TEXTSCALINGVARS := '_TEXTSCALINGVARS: $'$',$'$'' *)
(* @INPUTTAPFALSE := '_INPUTTAPFALSE: 0' *)

_SIMPLE : 0
_LINEWIDTH : 0
_NOCOLORS : 0,0
_POS : 40,280,111,296,75,288
_COLORS : 16777215,0,16776960,16777215,0
_VARIABLES : '','','','','','','',''
_THRESH : '','','',''
_DSP : '','Pess. Max',''
_ZOOM : ''
_INPUT : 0
_TEXT : 5,4294967285,400,0,876,0,0,0
_FONT : 'MS Sans Serif'
_EXEC : ''
_TEXTVARIABLES : '','','','',''
_COLORVARIABLES : '','','','','',''
_ACCESSLEVELS : 2,2,2,2,2,2,2,2
_OBJECT : 0,0
_THRESH2 : '','','',''
_INPUTTYPE : '','',''
_HIDDENINPUT : 0
_END_ELEM
(* @TEXTSCALINGVARS := '_TEXTSCALINGVARS: $'$',$'$'' *)
(* @EXTENDEDSIMPLESHAPE := '_SIMPLE: 0' *)
(* @INPUTTAPFALSE := '_INPUTTAPFALSE: 0' *)

_SIMPLE : 0
_LINEWIDTH : 0
_NOCOLORS : 1,1
_POS : 40,295,111,316,75,305
_COLORS : 16777215,0,16777215,0,0
_VARIABLES : '','','','','','','',''
_THRESH : '','','',''
_DSP : 'P2500.MaxBar','%.0f bar ',''
_ZOOM : ''
_INPUT : 1048576
_TEXT : 6,4294967283,400,0,877,0,0,0
_FONT : 'MS Sans Serif'
_EXEC : 'INTERN ASSIGN INPUTS.PresSelCalStbd[9]:=(FALSE)'
_TEXTVARIABLES : '','','','',''
_COLORVARIABLES : '','','','','',''
_ACCESSLEVELS : 2,2,2,2,2,2,2,2
_OBJECT : 0,1
_THRESH2 : '','','',''
_INPUTTYPE : '','',''
_HIDDENINPUT : 0
_END_ELEM
(* @TEXTSCALINGVARS := '_TEXTSCALINGVARS: $'$',$'$'' *)
(* @EXTENDEDSIMPLESHAPE := '_SIMPLE: 0' *)
(* @INPUTTAPFALSE := '_INPUTTAPFALSE: 0' *)

_SIMPLE : 0
_LINEWIDTH : 0
_NOCOLORS : 0,1
_POS : 50,60,101,81,75,70
_COLORS : 12828343,8388608,16776960,16777215,0
_VARIABLES : '','','','','','','',''
_THRESH : '','','',''
_DSP : '','WB',''
_ZOOM : ''
_INPUT : 0
_TEXT : 5,4294967285,400,0,879,0,0,0
_FONT : 'MS Sans Serif'
_EXEC : ''
_TEXTVARIABLES : '','','','',''
_COLORVARIABLES : '','','','','',''
_ACCESSLEVELS : 2,2,2,2,2,2,2,2
_OBJECT : 0,0
_THRESH2 : '','','',''
_INPUTTYPE : '','',''
_HIDDENINPUT : 0
_END_ELEM
(* @TEXTSCALINGVARS := '_TEXTSCALINGVARS: $'$',$'$'' *)
(* @EXTENDEDSIMPLESHAPE := '_SIMPLE: 0' *)
(* @INPUTTAPFALSE := '_INPUTTAPFALSE: 0' *)

_SIMPLE : 0
_LINEWIDTH : 0
_NOCOLORS : 0,0
_POS : 40,90,111,106,75,98
_COLORS : 16777215,0,16776960,16777215,0
_VARIABLES : '','','','','','','',''
_THRESH : '','','',''
_DSP : '','Time',''
_ZOOM : ''
_INPUT : 0
_TEXT : 5,4294967285,400,0,880,0,0,0
_FONT : 'MS Sans Serif'
_EXEC : ''
_TEXTVARIABLES : '','','','',''
_COLORVARIABLES : '','','','','',''
_ACCESSLEVELS : 2,2,2,2,2,2,2,2
_OBJECT : 0,0
_THRESH2 : '','','',''
_INPUTTYPE : '','',''
_HIDDENINPUT : 0
_END_ELEM
(* @TEXTSCALINGVARS := '_TEXTSCALINGVARS: $'$',$'$'' *)
(* @EXTENDEDSIMPLESHAPE := '_SIMPLE: 0' *)
(* @INPUTTAPFALSE := '_INPUTTAPFALSE: 0' *)

_SIMPLE : 0
_LINEWIDTH : 0
_NOCOLORS : 1,1
_POS : 40,495,111,516,75,505
_COLORS : 16777215,0,16777215,0,0
_VARIABLES : '','','','','','','',''
_THRESH : '','','',''
_DSP : 'PARAMS.stWBCfg.LP','%d ',''
_ZOOM : ''
_INPUT : 1048576
_TEXT : 6,4294967283,400,0,882,0,0,0
_FONT : 'MS Sans Serif'
_EXEC : 'INTERN ASSIGN INPUTS.PresSelCalStbd[9]:=(FALSE)'
_TEXTVARIABLES : '','','','',''
_COLORVARIABLES : '','','','','',''
_ACCESSLEVELS : 2,2,2,2,2,2,2,2
_OBJECT : 0,1
_THRESH2 : '','','',''
_INPUTTYPE : '1','2',''
_HIDDENINPUT : 0
_END_ELEM
(* @TEXTSCALINGVARS := '_TEXTSCALINGVARS: $'$',$'$'' *)
(* @EXTENDEDSIMPLESHAPE := '_SIMPLE: 0' *)
(* @INPUTTAPFALSE := '_INPUTTAPFALSE: 0' *)

_SIMPLE : 0
_LINEWIDTH : 0
_NOCOLORS : 0,0
_POS : 40,480,111,496,75,488
_COLORS : 16777215,0,16776960,16777215,0
_VARIABLES : '','','','','','','',''
_THRESH : '','','',''
_DSP : '','LP Pumps',''
_ZOOM : ''
_INPUT : 0
_TEXT : 5,4294967285,400,0,883,0,0,0
_FONT : 'MS Sans Serif'
_EXEC : ''
_TEXTVARIABLES : '','','','',''
_COLORVARIABLES : '','','','','',''
_ACCESSLEVELS : 2,2,2,2,2,2,2,2
_OBJECT : 0,0
_THRESH2 : '','','',''
_INPUTTYPE : '','',''
_HIDDENINPUT : 0
_END_ELEM
(* @TEXTSCALINGVARS := '_TEXTSCALINGVARS: $'$',$'$'' *)
(* @EXTENDEDSIMPLESHAPE := '_SIMPLE: 0' *)
(* @INPUTTAPFALSE := '_INPUTTAPFALSE: 0' *)

_POLY : 2
_LINEWIDTH : 0
_NOCOLORS : 1,1
_POLYSORT : 1
_POS : 75,470,30,470,120,470
_COLORS : 16777215,0,16777215,0,0
_VARIABLES : '','','',''
_THRESH : '','','',''
_INPUT : 0
_DSP : '','',''
_ZOOM : ''
_TEXT : 5,4294967284,400,0,884,0,0,0
_FONT : ''
_EXEC : ''
_TEXTVARIABLES : '','','','',''
_COLORVARIABLES : '','','','','',''
_ACCESSLEVELS : 2,2,2,2,2,2,2,2
_OBJECT : 0,0
_THRESH2 : '','','',''
_INPUTTYPE : '','',''
_HIDDENINPUT : 0
_END_ELEM
(* @TEXTSCALINGVARS := '_TEXTSCALINGVARS: $'$',$'$'' *)
(* @INPUTTAPFALSE := '_INPUTTAPFALSE: 0' *)

_SIMPLE : 0
_LINEWIDTH : 0
_NOCOLORS : 1,1
_POS : 25,340,126,361,75,350
_COLORS : 16777215,0,16777215,0,0
_VARIABLES : '','','','','','','',''
_THRESH : '','','',''
_DSP : 'PARAMS.stWBCfg.EVP_Pump_Min','Min: %.0f %% ',''
_ZOOM : ''
_INPUT : 1048576
_TEXT : 6,4294967283,400,0,885,0,0,0
_FONT : 'MS Sans Serif'
_EXEC : 'INTERN ASSIGN INPUTS.PresSelCalStbd[9]:=(FALSE)'
_TEXTVARIABLES : '','','','',''
_COLORVARIABLES : '','','','','',''
_ACCESSLEVELS : 2,2,2,2,2,2,2,2
_OBJECT : 0,1
_THRESH2 : '','','',''
_INPUTTYPE : '','',''
_HIDDENINPUT : 0
_END_ELEM
(* @TEXTSCALINGVARS := '_TEXTSCALINGVARS: $'$',$'$'' *)
(* @EXTENDEDSIMPLESHAPE := '_SIMPLE: 0' *)
(* @INPUTTAPFALSE := '_INPUTTAPFALSE: 0' *)

_SIMPLE : 0
_LINEWIDTH : 0
_NOCOLORS : 1,1
_POS : 25,360,126,381,75,370
_COLORS : 16777215,0,16777215,0,0
_VARIABLES : '','','','','','','',''
_THRESH : '','','',''
_DSP : 'PARAMS.stWBCfg.EVP_Pump_Max','Tgt: %.0f %% ',''
_ZOOM : ''
_INPUT : 1048576
_TEXT : 6,4294967283,400,0,886,0,0,0
_FONT : 'MS Sans Serif'
_EXEC : 'INTERN ASSIGN INPUTS.PresSelCalStbd[9]:=(FALSE)'
_TEXTVARIABLES : '','','','',''
_COLORVARIABLES : '','','','','',''
_ACCESSLEVELS : 2,2,2,2,2,2,2,2
_OBJECT : 0,1
_THRESH2 : '','','',''
_INPUTTYPE : '','',''
_HIDDENINPUT : 0
_END_ELEM
(* @TEXTSCALINGVARS := '_TEXTSCALINGVARS: $'$',$'$'' *)
(* @EXTENDEDSIMPLESHAPE := '_SIMPLE: 0' *)
(* @INPUTTAPFALSE := '_INPUTTAPFALSE: 0' *)

_SIMPLE : 0
_LINEWIDTH : 0
_NOCOLORS : 0,0
_POS : 40,325,111,341,75,333
_COLORS : 16777215,0,16776960,16777215,0
_VARIABLES : '','','','','','','',''
_THRESH : '','','',''
_DSP : '','PUMP EVP',''
_ZOOM : ''
_INPUT : 0
_TEXT : 5,4294967285,400,0,887,0,0,0
_FONT : 'MS Sans Serif'
_EXEC : ''
_TEXTVARIABLES : '','','','',''
_COLORVARIABLES : '','','','','',''
_ACCESSLEVELS : 2,2,2,2,2,2,2,2
_OBJECT : 0,0
_THRESH2 : '','','',''
_INPUTTYPE : '','',''
_HIDDENINPUT : 0
_END_ELEM
(* @TEXTSCALINGVARS := '_TEXTSCALINGVARS: $'$',$'$'' *)
(* @EXTENDEDSIMPLESHAPE := '_SIMPLE: 0' *)
(* @INPUTTAPFALSE := '_INPUTTAPFALSE: 0' *)

_SIMPLE : 0
_LINEWIDTH : 0
_NOCOLORS : 1,1
_POS : 25,400,126,421,75,410
_COLORS : 16777215,0,16777215,0,0
_VARIABLES : '','','','','','','',''
_THRESH : '','','',''
_DSP : 'PARAMS.stWBCfg.EVP_Pump_Inc','Inc: %.0f %%/s ',''
_ZOOM : ''
_INPUT : 1048576
_TEXT : 6,4294967283,400,0,888,0,0,0
_FONT : 'MS Sans Serif'
_EXEC : 'INTERN ASSIGN INPUTS.PresSelCalStbd[9]:=(FALSE)'
_TEXTVARIABLES : '','','','',''
_COLORVARIABLES : '','','','','',''
_ACCESSLEVELS : 2,2,2,2,2,2,2,2
_OBJECT : 0,1
_THRESH2 : '','','',''
_INPUTTYPE : '','',''
_HIDDENINPUT : 0
_END_ELEM
(* @TEXTSCALINGVARS := '_TEXTSCALINGVARS: $'$',$'$'' *)
(* @EXTENDEDSIMPLESHAPE := '_SIMPLE: 0' *)
(* @INPUTTAPFALSE := '_INPUTTAPFALSE: 0' *)

_SIMPLE : 0
_LINEWIDTH : 0
_NOCOLORS : 1,1
_POS : 25,420,126,441,75,430
_COLORS : 16777215,0,16777215,0,0
_VARIABLES : '','','','','','','',''
_THRESH : '','','',''
_DSP : 'PARAMS.stWBCfg.EVP_Pump_Dec','Dec: %.0f %%/s ',''
_ZOOM : ''
_INPUT : 1048576
_TEXT : 6,4294967283,400,0,889,0,0,0
_FONT : 'MS Sans Serif'
_EXEC : 'INTERN ASSIGN INPUTS.PresSelCalStbd[9]:=(FALSE)'
_TEXTVARIABLES : '','','','',''
_COLORVARIABLES : '','','','','',''
_ACCESSLEVELS : 2,2,2,2,2,2,2,2
_OBJECT : 0,1
_THRESH2 : '','','',''
_INPUTTYPE : '','',''
_HIDDENINPUT : 0
_END_ELEM
(* @TEXTSCALINGVARS := '_TEXTSCALINGVARS: $'$',$'$'' *)
(* @EXTENDEDSIMPLESHAPE := '_SIMPLE: 0' *)
(* @INPUTTAPFALSE := '_INPUTTAPFALSE: 0' *)

_SIMPLE : 0
_LINEWIDTH : 0
_NOCOLORS : 0,0
_POS : 25,385,126,401,75,393
_COLORS : 16777215,0,16776960,16777215,0
_VARIABLES : '','','','','','','',''
_THRESH : '','','',''
_DSP : '','PUMP EVP RAMP',''
_ZOOM : ''
_INPUT : 0
_TEXT : 5,4294967285,400,0,890,0,0,0
_FONT : 'MS Sans Serif'
_EXEC : ''
_TEXTVARIABLES : '','','','',''
_COLORVARIABLES : '','','','','',''
_ACCESSLEVELS : 2,2,2,2,2,2,2,2
_OBJECT : 0,0
_THRESH2 : '','','',''
_INPUTTYPE : '','',''
_HIDDENINPUT : 0
_END_ELEM
(* @TEXTSCALINGVARS := '_TEXTSCALINGVARS: $'$',$'$'' *)
(* @EXTENDEDSIMPLESHAPE := '_SIMPLE: 0' *)
(* @INPUTTAPFALSE := '_INPUTTAPFALSE: 0' *)

_SIMPLE : 0
_LINEWIDTH : 0
_NOCOLORS : 1,1
_POS : 25,105,126,126,75,115
_COLORS : 16777215,0,16777215,0,0
_VARIABLES : '','','','','','','',''
_THRESH : '','','',''
_DSP : 'PARAMS.stWBCfg.TimeMax_Idle','Idle: %.0f s ',''
_ZOOM : ''
_INPUT : 1048576
_TEXT : 6,4294967283,400,0,891,0,0,0
_FONT : 'MS Sans Serif'
_EXEC : 'INTERN ASSIGN INPUTS.PresSelCalStbd[9]:=(FALSE)'
_TEXTVARIABLES : '','','','',''
_COLORVARIABLES : '','','','','',''
_ACCESSLEVELS : 2,2,2,2,2,2,2,2
_OBJECT : 0,1
_THRESH2 : '','','',''
_INPUTTYPE : '','',''
_HIDDENINPUT : 0
_END_ELEM
(* @TEXTSCALINGVARS := '_TEXTSCALINGVARS: $'$',$'$'' *)
(* @EXTENDEDSIMPLESHAPE := '_SIMPLE: 0' *)
(* @INPUTTAPFALSE := '_INPUTTAPFALSE: 0' *)

_SIMPLE : 0
_LINEWIDTH : 0
_NOCOLORS : 1,1
_POS : 25,125,126,146,75,135
_COLORS : 16777215,0,16777215,0,0
_VARIABLES : '','','','','','','',''
_THRESH : '','','',''
_DSP : 'PARAMS.stWBCfg.TimeMax_Init','Init: %.0f s ',''
_ZOOM : ''
_INPUT : 1048576
_TEXT : 6,4294967283,400,0,892,0,0,0
_FONT : 'MS Sans Serif'
_EXEC : 'INTERN ASSIGN INPUTS.PresSelCalStbd[9]:=(FALSE)'
_TEXTVARIABLES : '','','','',''
_COLORVARIABLES : '','','','','',''
_ACCESSLEVELS : 2,2,2,2,2,2,2,2
_OBJECT : 0,1
_THRESH2 : '','','',''
_INPUTTYPE : '','',''
_HIDDENINPUT : 0
_END_ELEM
(* @TEXTSCALINGVARS := '_TEXTSCALINGVARS: $'$',$'$'' *)
(* @EXTENDEDSIMPLESHAPE := '_SIMPLE: 0' *)
(* @INPUTTAPFALSE := '_INPUTTAPFALSE: 0' *)

_SIMPLE : 0
_LINEWIDTH : 0
_NOCOLORS : 1,1
_POS : 25,165,126,186,75,175
_COLORS : 16777215,0,16777215,0,0
_VARIABLES : '','','','','','','',''
_THRESH : '','','',''
_DSP : 'PARAMS.stWBCfg.TimeMax_DumpFwd','Fwd: %.0f s ',''
_ZOOM : ''
_INPUT : 1048576
_TEXT : 6,4294967283,400,0,893,0,0,0
_FONT : 'MS Sans Serif'
_EXEC : 'INTERN ASSIGN INPUTS.PresSelCalStbd[9]:=(FALSE)'
_TEXTVARIABLES : '','','','',''
_COLORVARIABLES : '','','','','',''
_ACCESSLEVELS : 2,2,2,2,2,2,2,2
_OBJECT : 0,1
_THRESH2 : '','','',''
_INPUTTYPE : '','',''
_HIDDENINPUT : 0
_END_ELEM
(* @TEXTSCALINGVARS := '_TEXTSCALINGVARS: $'$',$'$'' *)
(* @EXTENDEDSIMPLESHAPE := '_SIMPLE: 0' *)
(* @INPUTTAPFALSE := '_INPUTTAPFALSE: 0' *)

_SIMPLE : 0
_LINEWIDTH : 0
_NOCOLORS : 0,0
_POS : 40,150,111,166,75,158
_COLORS : 16777215,0,16776960,16777215,0
_VARIABLES : '','','','','','','',''
_THRESH : '','','',''
_DSP : '','DUMP Time',''
_ZOOM : ''
_INPUT : 0
_TEXT : 5,4294967285,400,0,894,0,0,0
_FONT : 'MS Sans Serif'
_EXEC : ''
_TEXTVARIABLES : '','','','',''
_COLORVARIABLES : '','','','','',''
_ACCESSLEVELS : 2,2,2,2,2,2,2,2
_OBJECT : 0,0
_THRESH2 : '','','',''
_INPUTTYPE : '','',''
_HIDDENINPUT : 0
_END_ELEM
(* @TEXTSCALINGVARS := '_TEXTSCALINGVARS: $'$',$'$'' *)
(* @EXTENDEDSIMPLESHAPE := '_SIMPLE: 0' *)
(* @INPUTTAPFALSE := '_INPUTTAPFALSE: 0' *)

_SIMPLE : 0
_LINEWIDTH : 0
_NOCOLORS : 1,1
_POS : 25,185,126,206,75,195
_COLORS : 16777215,0,16777215,0,0
_VARIABLES : '','','','','','','',''
_THRESH : '','','',''
_DSP : 'PARAMS.stWBCfg.TimeMax_DumpAft','Aft: %.0f s ',''
_ZOOM : ''
_INPUT : 1048576
_TEXT : 6,4294967283,400,0,895,0,0,0
_FONT : 'MS Sans Serif'
_EXEC : 'INTERN ASSIGN INPUTS.PresSelCalStbd[9]:=(FALSE)'
_TEXTVARIABLES : '','','','',''
_COLORVARIABLES : '','','','','',''
_ACCESSLEVELS : 2,2,2,2,2,2,2,2
_OBJECT : 0,1
_THRESH2 : '','','',''
_INPUTTYPE : '','',''
_HIDDENINPUT : 0
_END_ELEM
(* @TEXTSCALINGVARS := '_TEXTSCALINGVARS: $'$',$'$'' *)
(* @EXTENDEDSIMPLESHAPE := '_SIMPLE: 0' *)
(* @INPUTTAPFALSE := '_INPUTTAPFALSE: 0' *)

_SIMPLE : 0
_LINEWIDTH : 0
_NOCOLORS : 1,1
_POS : 25,225,126,246,75,235
_COLORS : 16777215,0,16777215,0,0
_VARIABLES : '','','','','','','',''
_THRESH : '','','',''
_DSP : 'PARAMS.stWBCfg.TimeMax_MoveFwd','Fwd: %.0f s ',''
_ZOOM : ''
_INPUT : 1048576
_TEXT : 6,4294967283,400,0,896,0,0,0
_FONT : 'MS Sans Serif'
_EXEC : 'INTERN ASSIGN INPUTS.PresSelCalStbd[9]:=(FALSE)'
_TEXTVARIABLES : '','','','',''
_COLORVARIABLES : '','','','','',''
_ACCESSLEVELS : 2,2,2,2,2,2,2,2
_OBJECT : 0,1
_THRESH2 : '','','',''
_INPUTTYPE : '','',''
_HIDDENINPUT : 0
_END_ELEM
(* @TEXTSCALINGVARS := '_TEXTSCALINGVARS: $'$',$'$'' *)
(* @EXTENDEDSIMPLESHAPE := '_SIMPLE: 0' *)
(* @INPUTTAPFALSE := '_INPUTTAPFALSE: 0' *)

_SIMPLE : 0
_LINEWIDTH : 0
_NOCOLORS : 0,0
_POS : 40,210,111,226,75,218
_COLORS : 16777215,0,16776960,16777215,0
_VARIABLES : '','','','','','','',''
_THRESH : '','','',''
_DSP : '','MOVE Time',''
_ZOOM : ''
_INPUT : 0
_TEXT : 5,4294967285,400,0,897,0,0,0
_FONT : 'MS Sans Serif'
_EXEC : ''
_TEXTVARIABLES : '','','','',''
_COLORVARIABLES : '','','','','',''
_ACCESSLEVELS : 2,2,2,2,2,2,2,2
_OBJECT : 0,0
_THRESH2 : '','','',''
_INPUTTYPE : '','',''
_HIDDENINPUT : 0
_END_ELEM
(* @TEXTSCALINGVARS := '_TEXTSCALINGVARS: $'$',$'$'' *)
(* @EXTENDEDSIMPLESHAPE := '_SIMPLE: 0' *)
(* @INPUTTAPFALSE := '_INPUTTAPFALSE: 0' *)

_SIMPLE : 0
_LINEWIDTH : 0
_NOCOLORS : 1,1
_POS : 25,245,126,266,75,255
_COLORS : 16777215,0,16777215,0,0
_VARIABLES : '','','','','','','',''
_THRESH : '','','',''
_DSP : 'PARAMS.stWBCfg.TimeMax_MoveAft','Aft: %.0f s ',''
_ZOOM : ''
_INPUT : 1048576
_TEXT : 6,4294967283,400,0,898,0,0,0
_FONT : 'MS Sans Serif'
_EXEC : 'INTERN ASSIGN INPUTS.PresSelCalStbd[9]:=(FALSE)'
_TEXTVARIABLES : '','','','',''
_COLORVARIABLES : '','','','','',''
_ACCESSLEVELS : 2,2,2,2,2,2,2,2
_OBJECT : 0,1
_THRESH2 : '','','',''
_INPUTTYPE : '','',''
_HIDDENINPUT : 0
_END_ELEM
(* @TEXTSCALINGVARS := '_TEXTSCALINGVARS: $'$',$'$'' *)
(* @EXTENDEDSIMPLESHAPE := '_SIMPLE: 0' *)
(* @INPUTTAPFALSE := '_INPUTTAPFALSE: 0' *)

_SIMPLE : 1
_LINEWIDTH : 0
_NOCOLORS : 1,1
_POS : 900,105,1021,156,960,130
_COLORS : 16777215,0,16777215,0,0
_VARIABLES : '','','','','','','',''
_THRESH : '','','',''
_DSP : '','',''
_ZOOM : ''
_INPUT : 0
_TEXT : 5,4294967284,400,0,899,0,0,0
_FONT : ''
_EXEC : ''
_TEXTVARIABLES : '','','','',''
_COLORVARIABLES : '','','','','',''
_ACCESSLEVELS : 2,2,2,2,2,2,2,2
_OBJECT : 0,0
_THRESH2 : '','','',''
_INPUTTYPE : '','',''
_HIDDENINPUT : 0
_END_ELEM
(* @TEXTSCALINGVARS := '_TEXTSCALINGVARS: $'$',$'$'' *)
(* @EXTENDEDSIMPLESHAPE := '_SIMPLE: 0' *)
(* @INPUTTAPFALSE := '_INPUTTAPFALSE: 0' *)

_SIMPLE : 1
_LINEWIDTH : 0
_NOCOLORS : 1,1
_POS : 905,110,1016,151,960,130
_COLORS : 8421631,0,8454016,0,0
_VARIABLES : '','','','','','','',''
_THRESH : '','PARAMS.stWBCfg.EnScoopAF','PARAMS.stWBCfg.EnScoopAF',''
_DSP : '','ENABLE$R$NSCOOP ROT.',''
_ZOOM : ''
_INPUT : 65536
_TEXT : 5,4294967283,700,0,900,0,0,0
_FONT : 'MS Sans Serif'
_EXEC : ''
_TEXTVARIABLES : '','','','',''
_COLORVARIABLES : '','','','','',''
_ACCESSLEVELS : 2,2,2,2,2,2,2,2
_OBJECT : 0,0
_THRESH2 : '','','',''
_INPUTTYPE : '','',''
_HIDDENINPUT : 0
_END_ELEM
(* @TEXTSCALINGVARS := '_TEXTSCALINGVARS: $'$',$'$'' *)
(* @EXTENDEDSIMPLESHAPE := '_SIMPLE: 0' *)
(* @INPUTTAPFALSE := '_INPUTTAPFALSE: 0' *)
_KEYINFOLIST : 0
END_VISUALISATION
